
export const POPULAR_CITIES = [
  'Ciudad de México',
  'Monterrey',
  'Guadalajara',
  'Puebla',
  'Querétaro',
  'Mérida',
  'Cancún',
  'Tijuana',
  'León',
  'San Luis Potosí',
  'Toluca',
  'Veracruz',
  'Cuernavaca',
  'Aguascalientes',
  'Chihuahua'
];

export const COMMON_SPECIALTIES = [
    'Dentista - Odontólogo',
    'Psicólogo',
    'Médico general',
    'Hematólogo',
    'Internista',
    'Cardiólogo'
];

export const POPULAR_SPECIALTIES = [
  "Dentista - Odontólogo",
  "Psicólogo",
  "Pediatra",
  "Médico general",
  "Ginecólogo",
  "Internista",
  "Cirujano general",
  "Radiólogo",
  "Ortopedista",
  "Traumatólogo",
  "Oftalmólogo",
  "Psiquiatra",
  "Cardiólogo",
  "Nutricionista",
  "Otorrinolaringólogo",
  "Nutriólogo clínico",
  "Dermatólogo",
  "Fisioterapeuta",
  "Urólogo",
  "Cirujano plástico",
  "Gastroenterólogo",
  "Anestesiólogo",
  "Endoscopista",
  "Neurocirujano",
  "Endocrinólogo",
  "Nefrólogo",
  "Neonatólogo",
  "Psicoanalista",
  "Cirujano pediátrico",
  "Alergólogo"
];


export const SPECIALTY_CONDITIONS: Record<string, string[]> = {
  'Dentista - Odontólogo': ['Caries', 'Dolor de muelas', 'Infección dental', 'Bruxismo', 'Fracturas de dientes', 'Desgaste dental', 'Enfermedad periodontal - piorrea', 'Gingivitis', 'Sensibilidad dentaria', 'Alveolitis', 'Movilidad dentaria', 'Halitosis', 'Úlceras bucales', 'Impactación dental', 'Atrición dental', 'Fistula dental o en encía', 'Traumatismo dental'],
  'Psicólogo': ['Ansiedad', 'Depresión', 'Duelo', 'Estrés', 'Codependencia', 'Ataques de pánico', 'Bullying (acoso escolar)', 'Estrés laboral', 'Angustia', 'Baja autoestima', 'Luto', 'Tristeza', 'Dependencia emocional', 'Control de emociones', 'Trastorno de adaptación'],
  'Pediatra': ['Fiebre en niños', 'Bronquiolitis', 'Estreñimiento en niños', 'Anemia ferropénica en niños', 'Dermatitis del pañal', 'Cólico infantil', 'Varicela', 'Alergia alimentaria', 'Infección urinaria en niños', 'Convulsiones febriles', 'Crup'],
  'Médico general': ['Resfriado común', 'Gastroenteritis aguda', 'Dolor abdominal', 'Faringitis', 'Heridas', 'Deshidratación', 'Dolor de cabeza'],
  'Ginecólogo': ['Miomas uterinos', 'Embarazo', 'Menopausia', 'Amenaza de aborto', 'Sangrado uterino disfuncional', 'Infertilidad', 'Quistes ováricos', 'Endometriosis', 'Ovarios poliquísticos', 'Cervicitis', 'VPH', 'Candidiasis vaginal'],
  'Internista': ['Hipertensión', 'Diabetes', 'Dislipidemia', 'Insuficiencia cardíaca', 'Neumonía', 'Hígado graso', 'Lupus', 'Fatiga crónica'],
  'Cirujano general': ['Apendicitis', 'Hernia inguinal', 'Hernia umbilical', 'Colecistitis aguda', 'Cálculos biliares', 'Hernia hiatal', 'Abdomen agudo', 'Adherencias'],
  'Radiólogo': ['Diagnóstico de fracturas', 'Detección de tumores', 'Evaluación de órganos internos', 'Seguimiento de embarazo (ultrasonido)'],
  'Ortopedista': ['Escoliosis', 'Juanetes', 'Pie plano', 'Osteoartritis', 'Desgaste de rodilla', 'Curvatura de la columna', 'Postura jorobada', 'Rodilla vara'],
  'Traumatólogo': ['Fracturas', 'Ciática', 'Lesiones deportivas', 'Esguince', 'Hernia de disco', 'Lesiones de Menisco', 'Tendinitis', 'Fractura de fémur', 'Fractura de cadera'],
  'Oftalmólogo': ['Cataratas', 'Miopía', 'Astigmatismo', 'Glaucoma', 'Retinopatía diabética', 'Desprendimiento de retina', 'Conjuntivitis', 'Presbicia', 'Estrabismo'],
  'Psiquiatra': ['Trastorno bipolar', 'Esquizofrenia', 'Trastorno obsesivo compulsivo (TOC)', 'Depresión mayor', 'Psicosis', 'Trastorno de conducta', 'Adicciones'],
  'Cardiólogo': ['Arritmias', 'Infarto agudo de miocardio', 'Insuficiencia cardíaca', 'Angina de pecho', 'Síncope', 'Fibrilación auricular', 'Taquicardia', 'Bradicardia'],
  'Nutricionista': ['Control de peso', 'Dieta equilibrada', 'Educación alimentaria', 'Planificación de comidas'],
  'Otorrinolaringólogo': ['Sinusitis', 'Otitis', 'Amigdalitis', 'Rinitis alérgica', 'Vértigo postural benigno', 'Ronquido', 'Pólipos nasales', 'Cerumen (cera del oído)'],
  'Nutriólogo clínico': ['Obesidad', 'Desnutrición', 'Sobrepeso', 'Resistencia a la insulina', 'Diabetes tipo 2', 'Intolerancia a la lactosa'],
  'Dermatólogo': ['Acné', 'Psoriasis', 'Cáncer de piel', 'Vitiligo', 'Alopecia', 'Rosácea', 'Melasma', 'Dermatitis atópica', 'Verrugas', 'Caspa'],
  'Fisioterapeuta': ['Rehabilitación física', 'Contractura cervical', 'Dolor muscular', 'Parálisis facial', 'Epicondilitis humeral', 'Linfedema'],
  'Urólogo': ['Cáncer de próstata', 'Disfunción eréctil', 'Cálculos renales', 'Varicocele', 'Incontinencia urinaria', 'Eyaculación precoz', 'Fimosis', 'Balanitis'],
  'Cirujano plástico': ['Gigantomastia', 'Cicatriz queloide', 'Labio leporino y paladar hendido', 'Quemaduras', 'Reconstrucción mamaria'],
  'Gastroenterólogo': ['Gastritis', 'Colon irritable', 'Reflujo gastroesofágico', 'Diverticulitis', 'Cirrosis', 'Hepatitis', 'Celiaquía'],
  'Terapeuta complementario': ['Manejo del estrés', 'Bienestar holístico', 'Terapias de relajación'],
  'Anestesiólogo': ['Manejo del dolor perioperatorio', 'Anestesia local', 'Anestesia general', 'Sedación'],
  'Especialista en Obesidad y Delgadez': ['Obesidad mórbida', 'Delgadez extrema', 'Trastorno por atracón', 'Manejo metabólico del peso'],
  'Endoscopista': ['Detección de úlceras', 'Pólipos gástricos', 'Biopsias digestivas', 'Esofagitis'],
  'Neurocirujano': ['Tumor cerebral', 'Aneurisma cerebral', 'Hemorragia cerebral', 'Hidrocefalia', 'Compresión de la médula espinal'],
  'Endocrinólogo': ['Hipertiroidismo', 'Hipotiroidismo', 'Bocio', 'Nódulo tiroideo', 'Síndrome de Cushing', 'Ginecomastia'],
  'Especialista en Rehabilitación y Medicina Física': ['Recuperación post-ictus', 'Manejo de discapacidad', 'Fisiatría', 'Terapia de movilidad'],
  'Nefrólogo': ['Falla renal crónica', 'Insuficiencia renal aguda', 'Glomerulonefritis', 'Síndrome nefrótico', 'Nefropatía diabética'],
  'Neonatólogo': ['Bebé prematuro', 'Ictericia del recién nacido', 'Crisis respiratoria en recién nacidos'],
  'Psicoanalista': ['Neurosis histérica', 'Conflictos inconscientes', 'Análisis de la personalidad'],
  'Cirujano pediátrico': ['Estenosis pilórica', 'Criptorquidia', 'Divertículo de Meckel', 'Ano imperforado', 'Gastrosquisis'],
  'Alergólogo': ['Urticaria', 'Alergia a fármacos', 'Asma bronquial', 'Alergias nasales', 'Alergia alimentaria'],
  'Neumólogo': ['EPOC', 'Asma', 'Bronquitis crónica', 'Fibrosis pulmonar', 'Apnea del sueño'],
  'Reumatólogo': ['Artritis reumatoide', 'Lupus', 'Fibromialgia', 'Esclerosis múltiple', 'Espondilitis anquilosante', 'Gota'],
  'Homeópata': ['Tratamientos naturales', 'Enfoque individualizado', 'Manejo de síntomas crónicos'],
  'Neurólogo': ['Epilepsia', 'Migraña', 'Enfermedad de Parkinson', 'Alzheimer', 'Esclerosis múltiple', 'Derrame cerebral'],
  'Oncólogo médico': ['Cáncer de pulmón', 'Leucemia', 'Linfoma', 'Tratamiento con quimioterapia'],
  'Cirujano maxilofacial': ['Diente impactado', 'Prognatismo', 'Traumatismo facial', 'Asimetría facial'],
  'Angiólogo': ['Venas varicosas', 'Insuficiencia venosa', 'Pie Diabético', 'Trombosis venosa profunda', 'Flebitis'],
  'Especialista en Medicina Crítica y Terapia Intensiva': ['Shock séptico', 'Falla multiorgánica', 'Soporte vital', 'Monitoreo crítico'],
  'Geriatra': ['Demencia', 'Delirium', 'Síndrome de caídas', 'Fragilidad en el anciano'],
  'Cirujano oncólogo': ['Cáncer de mama', 'Cáncer colorrectal', 'Cáncer de tiroides', 'Cáncer del estómago'],
  'Proctólogo': ['Hemorroides', 'Fisura anal', 'Absceso anal', 'Fístula anal', 'Prolapso rectal'],
  'Audiólogo': ['Sordera', 'Hipoacusia relacionada con la edad', 'Tinnitus'],
  'Hematólogo': ['Anemia', 'Hemofilia', 'Trombocitopenia', 'Mieloma múltiple', 'Leucemia'],
  'Médico de familia': ['Seguimiento preventivo', 'Control de salud familiar', 'Vacunación'],
  'Infectólogo': ['Coronavirus COVID-19', 'Tuberculosis pulmonar', 'VIH/Sida', 'Hepatitis infecciosa'],
  'Médico estético': ['Cicatrices de acné', 'Envejecimiento cutáneo', 'Reducción de grasa localizada'],
  'Diabetólogo': ['Diabetes tipo 1', 'Diabetes tipo 2', 'Pie diabético'],
  'Acupuntor': ['Alivio del dolor crónico', 'Equilibrio energético', 'Tratamiento de migrañas'],
  'Quiropráctico': ['Alineación de columna', 'Dolor de espalda', 'Ajustes articulares'],
  'Optometrista': ['Graduación de lentes', 'Examen de agudeza visual', 'Detección de problemas de enfoque'],
  'Sexólogo': ['Disfunción eréctil', 'Eyaculación precoz', 'Deseo sexual inhibido', 'Aversión al sexo'],
  'Cirujano cardiovascular y torácico': ['Estenosis aórtica', 'Estenosis mitral', 'Aneurisma de aorta'],
  'Inmunólogo': ['Trastornos por inmunodeficiencia', 'Inmunoterapia', 'Rechazo al trasplante'],
  'Psicopedagogo': ['Trastornos del aprendizaje', 'Dislexia', 'TDAH'],
  'Neurólogo pediatra': ['Autismo', 'Parálisis cerebral', 'Epilepsia infantil', 'TDAH'],
  'Cardiólogo pediátrico': ['Cardiopatía congénita', 'Comunicación interauricular'],
  'Enfermero': ['Cuidado de heridas', 'Administración de medicamentos', 'Monitoreo de signos vitales'],
  'Odontólogo pediatra': ['Dentición', 'Caries en niños', 'Selladores dentales'],
  'Algólogo': ['Dolor oncológico', 'Dolor neuropático', 'Manejo de dolor terminal'],
  'Especialista en Medicina del Deporte': ['Rendimiento físico', 'Prevención de lesiones', 'Traumatismos deportivos'],
  'Ginecólogo oncológico': ['Cáncer del cuello uterino', 'Cáncer de ovario', 'Cáncer endometrial'],
  'Radioterapeuta': ['Tratamiento de tumores con radiación', 'Radioterapia paliativa'],
  'Neumólogo pediatra': ['Asma pediátrico', 'Bronconeumonía infantil'],
  'Urgenciólogo': ['Abdomen agudo', 'Traumatismos graves', 'Infartos'],
  'Endocrinólogo pediátrico': ['Pubertad precoz', 'Diabetes tipo 1 en niños', 'Problemas de crecimiento'],
  'Logopeda': ['Tartamudeo', 'Dislalia', 'Trastornos de la voz'],
  'Genetista': ['Síndrome de Down', 'Enfermedades raras hereditarias', 'Asesoramiento genético'],
  'Cirujano estético y cosmético': ['Rinoplastia estética', 'Liposucción', 'Aumento de busto'],
  'Gastroenterólogo pediátrico': ['Reflujo en bebés', 'Estreñimiento infantil'],
  'Psiquiatra infantil': ['Trastorno del espectro autista', 'Depresión infantil', 'TDAH'],
  'Neurofisiólogo': ['Electroencefalograma', 'Mapeo cerebral', 'Electromiografía'],
  'Cirujano vascular': ['Aneurismas', 'Bypass vascular', 'Angioplastias'],
  'Cirujano bariatra': ['Bypass gástrico', 'Manga gástrica', 'Cirugía para obesidad'],
  'Dermatólogo pediátrico': ['Dermatitis atópica infantil', 'Hemangiomas'],
  'Nefrólogo pediatra': ['Síndrome nefrótico infantil', 'Infección urinaria recurrente en niños'],
  'Analista clínico': ['Pruebas de glucosa', 'Hemogramas', 'Exámenes de orina y heces']
};

// Reusing the slugify from your code for internal consistency in constants
export const slugify = (text: string) => {
  return text.toString().toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
};

export const ALL_CITIES = [
  "Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León",
  "Mérida", "Cancún", "Querétaro", "Toluca", "Chihuahua", "Hermosillo",
  "Saltillo", "Mexicali", "Aguascalientes", "San Luis Potosí", "Culiacán",
  "Acapulco", "Morelia", "Veracruz"
];

export const DISEASE_RELATED_SPECIALTIES: Record<string, string[]> = {
  'Ansiedad': ['Psicólogo', 'Psiquiatra'],
  'Depresión': ['Psicólogo', 'Psiquiatra'],
  'Duelo': ['Psicólogo'],
  'Estrés': ['Psicólogo'],
  'Codependencia': ['Psicólogo'],
  'Hipertensión': ['Cardiólogo', 'Internista'],
  'Caries': ['Dentista - Odontólogo'],
  'Estrés postraumático': ['Psicólogo', 'Psiquiatra'],
  'Trastorno de conducta': ['Psiquiatra', 'Psicólogo'],
  'Diabetes': ['Endocrinólogo', 'Diabetólogo', 'Internista'],
  'Dislipidemia': ['Internista', 'Endocrinólogo', 'Cardiólogo'],
  'Depresión en adolescentes': ['Psiquiatra infantil', 'Psicólogo'],
  'Bruxismo': ['Dentista - Odontólogo', 'Fisioterapeuta'],
  'Síndrome metabólico': ['Endocrinólogo', 'Internista', 'Nutriólogo clínico'],
  'Dolor de muelas': ['Dentista - Odontólogo'],
  'Obesidad': ['Especialista en Obesidad y Delgadez', 'Nutriólogo clínico', 'Endocrinólogo'],
  'Trastorno obsesivo compulsivo (TOC)': ['Psiquiatra', 'Psicólogo'],
  'Infección dental': ['Dentista - Odontólogo'],
  'Sobrepeso': ['Nutriólogo clínico', 'Especialista en Obesidad y Delgadez'],
  'Fracturas de dientes': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Desgaste dental': ['Dentista - Odontólogo'],
  'Ataques de pánico': ['Psicólogo', 'Psiquiatra'],
  'Bullying (acoso escolar)': ['Psicólogo', 'Psicopedagogo'],
  'Pérdida de dientes': ['Dentista - Odontólogo'],
  'Dientes desalineados': ['Dentista - Odontólogo'],
  'Dientes apiñados': ['Dentista - Odontólogo'],
  'Estrés laboral': ['Psicólogo'],
  'Angustia': ['Psicólogo', 'Psiquiatra'],
  'Enfermedad periodontal - piorrea': ['Dentista - Odontólogo'],
  'Lesiones deportivas': ['Especialista en Medicina del Deporte', 'Traumatólogo', 'Fisioterapeuta'],
  'Trastorno de ansiedad': ['Psicólogo', 'Psiquiatra'],
  'Trastorno de ansiedad generalizada': ['Psicólogo', 'Psiquiatra'],
  'Gastritis': ['Gastroenterólogo', 'Internista'],
  'Colon irritable': ['Gastroenterólogo', 'Internista'],
  'Virus del papiloma humano (VPH)': ['Ginecólogo', 'Urólogo', 'Dermatólogo'],
  'Diabetes gestacional': ['Ginecólogo', 'Endocrinólogo'],
  'Miomas uterinos': ['Ginecólogo'],
  'Embarazo': ['Ginecólogo'],
  'Trastornos de la personalidad': ['Psiquiatra', 'Psicólogo'],
  'Menopausia': ['Ginecólogo', 'Endocrinólogo'],
  'Ciática': ['Traumatólogo', 'Ortopedista', 'Fisioterapeuta'],
  'Trastorno de hiperactividad y déficit de atención (TDAH)': ['Neurólogo pediatra', 'Psiquiatra infantil', 'Psicopedagogo'],
  'Depresión crónica': ['Psiquiatra', 'Psicólogo'],
  'Conducta agresiva': ['Psicólogo', 'Psiquiatra'],
  'Embarazo de alto riesgo': ['Ginecólogo'],
  'Desnutrición': ['Nutriólogo clínico', 'Pediatra'],
  'Endometriosis': ['Ginecólogo'],
  'Insuficiencia cardíaca': ['Cardiólogo'],
  'Amenaza de aborto': ['Ginecólogo'],
  'Adicciones': ['Psiquiatra', 'Psicólogo'],
  'Apendicitis': ['Cirujano general'],
  'Comportamiento suicida': ['Psiquiatra', 'Psicólogo'],
  'Síndrome de pinzamiento del hombro': ['Traumatólogo', 'Ortopedista', 'Fisioterapeuta'],
  'Faringitis': ['Otorrinolaringólogo', 'Médico general'],
  'Diabetes tipo 2': ['Endocrinólogo', 'Diabetólogo', 'Internista'],
  'Sangrado uterino disfuncional': ['Ginecólogo'],
  'Asma': ['Neumólogo', 'Alergólogo'],
  'Gingivitis': ['Dentista - Odontólogo'],
  'Maltrato psicológico y abandono infantil': ['Psicólogo', 'Pediatra'],
  'Abdomen agudo': ['Cirujano general', 'Urgenciólogo'],
  'Desorden de ansiedad por separación': ['Psiquiatra infantil', 'Psicólogo'],
  'Hernia de disco': ['Traumatólogo', 'Neurocirujano'],
  'Tendinitis del manguito de los rotadores': ['Traumatólogo', 'Fisioterapeuta'],
  'Fobia específica o simple': ['Psicólogo'],
  'Hernia inguinal': ['Cirujano general'],
  'Neumonía': ['Neumólogo', 'Internista'],
  'Colecistitis aguda': ['Cirujano general'],
  'Cataratas': ['Oftalmólogo'],
  'Reflujo gastroesofágico': ['Gastroenterólogo', 'Internista'],
  'Diverticulitis': ['Gastroenterólogo', 'Cirujano general'],
  'Enfermedad articular degenerativa': ['Reumatólogo', 'Ortopedista'],
  'Tendinitis': ['Traumatólogo', 'Fisioterapeuta'],
  'Radiculopatía lumbar': ['Traumatólogo', 'Neurocirujano'],
  'Depresión neurótica (distimia)': ['Psiquiatra', 'Psicólogo'],
  'Infertilidad': ['Ginecólogo', 'Urólogo'],
  'Rinitis alérgica': ['Alergólogo', 'Otorrinolaringólogo'],
  'Cálculos biliares': ['Cirujano general', 'Gastroenterólogo'],
  'Periodontitis': ['Dentista - Odontólogo'],
  'Manchas en dientes': ['Dentista - Odontólogo'],
  'Absceso dental': ['Dentista - Odontólogo'],
  'Dolor abdominal': ['Gastroenterólogo', 'Médico general'],
  'Miopía': ['Oftalmólogo', 'Optometrista'],
  'Osteoporosis': ['Reumatólogo', 'Endocrinólogo', 'Internista'],
  'Diente retenido': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Lesión de Ligamentarias de Rodilla': ['Traumatólogo', 'Ortopedista'],
  'Contractura cervical': ['Fisioterapeuta', 'Ortopedista'],
  'Lesiones de cartílago articular': ['Traumatólogo', 'Ortopedista'],
  'Anorexia nerviosa': ['Psiquiatra', 'Nutriólogo clínico', 'Psicólogo'],
  'Asma pediátrico': ['Neumólogo pediatra', 'Pediatra'],
  'Trastornos de la articulación temporomandibular': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Lesiones de Menisco': ['Traumatólogo', 'Ortopedista'],
  'Luto': ['Psicólogo'],
  'Dermatitis atópica': ['Dermatólogo', 'Alergólogo'],
  'Astigmatismo': ['Oftalmólogo', 'Optometrista'],
  'Depresión grave': ['Psiquiatra', 'Psicólogo'],
  'Colecistitis crónica': ['Cirujano general'],
  'Hernia hiatal': ['Gastroenterólogo', 'Cirujano general'],
  'Faringitis bacteriana': ['Otorrinolaringólogo', 'Infectólogo'],
  'Sensibilidad dentaria': ['Dentista - Odontólogo'],
  'Hernia': ['Cirujano general'],
  'Bulimia nerviosa': ['Psiquiatra', 'Psicólogo', 'Nutriólogo clínico'],
  'Hernia umbilical': ['Cirujano general'],
  'Reflujo gastroesofágico en bebés': ['Gastroenterólogo pediátrico', 'Pediatra'],
  'Dermatitis del pañal': ['Pediatra', 'Dermatólogo'],
  'Cólico infantil': ['Pediatra'],
  'Alveolitis': ['Dentista - Odontólogo'],
  'Colitis': ['Gastroenterólogo'],
  'Dolor muscular': ['Fisioterapeuta', 'Traumatólogo'],
  'Cáncer de piel': ['Dermatólogo', 'Cirujano oncólogo'],
  'Retinopatía diabética': ['Oftalmólogo'],
  'Movilidad dentaria': ['Dentista - Odontólogo'],
  'Demencia': ['Geriatra', 'Neurólogo', 'Psiquiatra'],
  'Bronquiolitis': ['Pediatra', 'Neumólogo pediatra'],
  'Conjuntivitis': ['Oftalmólogo'],
  'Nutrición inadecuada': ['Nutriólogo clínico', 'Pediatra'],
  'Mordida abierta': ['Dentista - Odontólogo'],
  'Diarrea': ['Médico general', 'Gastroenterólogo'],
  'Cáncer de próstata': ['Urólogo', 'Oncólogo médico'],
  'Anemia': ['Hematólogo', 'Internista'],
  'Cardiomiopatía isquémica': ['Cardiólogo'],
  'Trastornos del aprendizaje': ['Psicopedagogo', 'Psicólogo'],
  'Halitosis': ['Dentista - Odontólogo'],
  'Glaucoma': ['Oftalmólogo'],
  'Síndrome del ojo seco': ['Oftalmólogo'],
  'Fascitis plantar': ['Traumatólogo', 'Fisioterapeuta'],
  'Amigdalitis': ['Otorrinolaringólogo'],
  'Fiebre en niños': ['Pediatra'],
  'Alergia alimentaria': ['Alergólogo', 'Pediatra'],
  'Diente impactado': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Migraña': ['Neurólogo'],
  'Hipermetropía': ['Oftalmólogo', 'Optometrista'],
  'Hiperlipidemia': ['Endocrinólogo', 'Internista'],
  'Sinusitis': ['Otorrinolaringólogo'],
  'Infección urinaria en niños': ['Pediatra', 'Nefrólogo pediatra'],
  'Oclusión dental defectuosa': ['Dentista - Odontólogo'],
  'Lesión de Manguito Rotador': ['Traumatólogo', 'Ortopedista'],
  'Acné': ['Dermatólogo'],
  'Pterigión': ['Oftalmólogo'],
  'Arritmias': ['Cardiólogo'],
  'Pie plano': ['Ortopedista'],
  'Baja autoestima': ['Psicólogo'],
  'Hipertiroidismo': ['Endocrinólogo'],
  'Sobremordida': ['Dentista - Odontólogo'],
  'Hipercolesterolemia': ['Endocrinólogo', 'Internista'],
  'Esquizofrenia': ['Psiquiatra'],
  'Atrición dental': ['Dentista - Odontólogo'],
  'Trastorno bipolar': ['Psiquiatra'],
  'Alergias': ['Alergólogo'],
  'Vértigo postural benigno': ['Otorrinolaringólogo'],
  'Fracturas': ['Traumatólogo', 'Ortopedista'],
  'Lumbalgia': ['Ortopedista', 'Fisioterapeuta', 'Traumatólogo'],
  'Dolor de cabeza por contracción muscular': ['Psicólogo', 'Fisioterapeuta'],
  'Cefalea tensional': ['Neurólogo', 'Psicólogo'],
  'Infarto agudo de miocardio': ['Cardiólogo', 'Urgenciólogo'],
  'Impactación dental': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Angina': ['Cardiólogo'],
  'Prognatismo': ['Cirujano maxilofacial', 'Dentista - Odontólogo'],
  'Cáncer renal': ['Urólogo', 'Oncólogo médico'],
  'Gastroenteritis': ['Gastroenterólogo', 'Médico general'],
  'Síntomas gastrointestinales': ['Gastroenterólogo'],
  'Disfunción eréctil': ['Urólogo', 'Sexólogo'],
  'Cáncer del colon': ['Cirujano oncólogo', 'Gastroenterólogo', 'Proctólogo'],
  'Úlceras bucales': ['Dentista - Odontólogo'],
  'Gastritis por estrés': ['Gastroenterólogo', 'Psicólogo'],
  'Trastornos de la ATM': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Curvatura de la columna': ['Ortopedista'],
  'Alergias nasales': ['Alergólogo', 'Otorrinolaringólogo'],
  'Otitis': ['Otorrinolaringólogo'],
  'Alopecia androgénica': ['Dermatólogo'],
  'Epilepsia': ['Neurólogo'],
  'Alopecia areata': ['Dermatólogo'],
  'Incontinencia urinaria de esfuerzo': ['Urólogo', 'Ginecólogo'],
  'Enfermedad de transmisión sexual (ETS)': ['Infectólogo', 'Urólogo', 'Ginecólogo'],
  'Bebé prematuro': ['Neonatólogo', 'Pediatra'],
  'Verrugas': ['Dermatólogo'],
  'Infarto de miocardio': ['Cardiólogo'],
  'Bronquitis crónica': ['Neumólogo'],
  'Desprendimiento de retina': ['Oftalmólogo'],
  'Eyaculación precoz': ['Urólogo', 'Sexólogo'],
  'Pólipos nasales': ['Otorrinolaringólogo'],
  'Cáncer de pulmón': ['Oncólogo médico', 'Neumólogo'],
  'Enfermedad de Parkinson': ['Neurólogo'],
  'Fibrilación auricular': ['Cardiólogo'],
  'Ausencia dentaria': ['Dentista - Odontólogo'],
  'Bursitis': ['Traumatólogo', 'Fisioterapeuta'],
  'Laringitis': ['Otorrinolaringólogo'],
  'Luxación Acromioclavicular': ['Traumatólogo'],
  'Cáncer del cuello uterino': ['Ginecólogo oncológico'],
  'Cálculos en las vías urinarias': ['Urólogo'],
  'Enfermedad de Alzheimer': ['Neurólogo', 'Geriatra'],
  'Cáncer de mama': ['Cirujano oncólogo', 'Ginecólogo oncológico'],
  'Quistes ováricos': ['Ginecólogo'],
  'Bradicardia': ['Cardiólogo'],
  'Neurosis histérica': ['Psiquiatra', 'Psicoanalista'],
  'Hígado graso': ['Gastroenterólogo', 'Internista'],
  'Melasma': ['Dermatólogo'],
  'Depresión mayor': ['Psiquiatra', 'Psicólogo'],
  'Disoclusión de los dientes': ['Dentista - Odontólogo'],
  'Gastroenteritis aguda': ['Gastroenterólogo', 'Médico general'],
  'Cáncer de tiroides': ['Endocrinólogo', 'Cirujano oncólogo'],
  'Varicocele': ['Urólogo'],
  'Estreñimiento': ['Gastroenterólogo'],
  'Cáncer testicular': ['Urólogo', 'Oncólogo médico'],
  'Cardiopatía hipertensiva': ['Cardiólogo'],
  'Enfermedad benigna de las mamas': ['Ginecólogo'],
  'Cicatriz hipertrófica': ['Dermatólogo', 'Cirujano plástico'],
  'Síndrome de los ovarios poliquísticos (PCOS)': ['Endocrinólogo', 'Ginecólogo'],
  'Contracturas musculares': ['Fisioterapeuta'],
  'Trastornos del sueño': ['Psiquiatra', 'Neurólogo', 'Psicólogo'],
  'Nefropatía diabética': ['Nefrólogo', 'Endocrinólogo'],
  'Cáncer de los ovarios': ['Ginecólogo oncológico'],
  'Cicatriz queloide': ['Dermatólogo', 'Cirujano plástico'],
  'Pancreatitis': ['Gastroenterólogo', 'Cirujano general'],
  'Apnea del sueño de tipo obstructivo': ['Neumólogo', 'Otorrinolaringólogo'],
  'Cáncer vesical': ['Urólogo', 'Oncólogo médico'],
  'Cambios precancerosos del cuello uterino': ['Ginecólogo oncológico'],
  'Trastornos de la menstruación': ['Ginecólogo'],
  'Hipertrofia (hiperplasia) prostática benigna': ['Urólogo'],
  'Fobia social': ['Psicólogo', 'Psiquiatra'],
  'Trastorno de la conducta alimentaria': ['Psiquiatra', 'Psicólogo', 'Nutriólogo clínico'],
  'Cirrosis': ['Gastroenterólogo'],
  'Psoriasis': ['Dermatólogo'],
  'Hemorroides': ['Proctólogo', 'Cirujano general'],
  'Ovarios poliquísticos': ['Ginecólogo', 'Endocrinólogo'],
  'Obesidad mórbida': ['Cirujano bariatra', 'Especialista en Obesidad y Delgadez'],
  'Depresión posparto': ['Psiquiatra', 'Psicólogo', 'Ginecólogo'],
  'Vitiligo': ['Dermatólogo'],
  'Síndrome de burnout': ['Psicólogo'],
  'Pie Diabético': ['Angiólogo', 'Internista', 'Endocrinólogo'],
  'Osteoartrosis': ['Reumatólogo', 'Ortopedista'],
  'Manchas de la edad': ['Dermatólogo'],
  'Distimia': ['Psiquiatra', 'Psicólogo'],
  'Conjuntivitis alérgica': ['Oftalmólogo', 'Alergólogo'],
  'Fracturas por compresión o aplastamiento vertebral': ['Ortopedista', 'Neurocirujano'],
  'Hipotiroidismo': ['Endocrinólogo'],
  'Desgaste de cadera': ['Ortopedista', 'Traumatólogo'],
  'Resfriado común': ['Médico general'],
  'Artritis reumatoide': ['Reumatólogo'],
  'Hepatitis': ['Gastroenterólogo', 'Infectólogo'],
  'Codo de tenista': ['Fisioterapeuta', 'Traumatólogo'],
  'Diabetes tipo 1': ['Endocrinólogo', 'Diabetólogo'],
  'Depresión en los ancianos': ['Geriatra', 'Psiquiatra', 'Psicólogo'],
  'Preeclampsia': ['Ginecólogo'],
  'Sangrado uterino anormal': ['Ginecólogo'],
  'Trastorno de adaptación': ['Psicólogo'],
  'Urticaria': ['Dermatólogo', 'Alergólogo'],
  'Dolor en la inserción del talón': ['Ortopedista', 'Podólogo'],
  'Cálculos renales': ['Urólogo'],
  'Embarazo ectópico': ['Ginecólogo'],
  'Dermatitis alérgica': ['Dermatólogo', 'Alergólogo'],
  'Cáncer colorrectal': ['Cirujano oncólogo', 'Gastroenterólogo'],
  'Asma bronquial': ['Neumólogo'],
  'Enfermedad de la vesícula biliar': ['Cirujano general', 'Gastroenterólogo'],
  'Lesión facial': ['Cirujano plástico', 'Cirujano maxilofacial'],
  'Heridas': ['Médico general', 'Cirujano general'],
  'Esofagitis por reflujo': ['Gastroenterólogo'],
  'EIP (infección genital femenina)': ['Ginecólogo'],
  'Coronavirus COVID-19': ['Infectólogo', 'Neumólogo', 'Internista'],
  'Coledocolitiasis': ['Gastroenterólogo', 'Cirujano general'],
  'Tumor cerebral en adultos': ['Neurocirujano', 'Oncólogo médico'],
  'Anorexia': ['Psiquiatra', 'Psicólogo', 'Nutriólogo clínico'],
  'Tendinitis, esguinces articulares': ['Traumatólogo', 'Fisioterapeuta'],
  'Fibromialgia': ['Reumatólogo'],
  'Lunar': ['Dermatólogo'],
  'Queratocono': ['Oftalmólogo'],
  'Hemorragia cerebral': ['Neurocirujano', 'Neurólogo'],
  'Embarazo en la adolescencia': ['Ginecólogo'],
  'Enfermedad de los ovarios poliquísticos': ['Ginecólogo', 'Endocrinólogo'],
  'Delgadez': ['Nutriólogo clínico', 'Endocrinólogo', 'Especialista en Obesidad y Delgadez'],
  'Colelitiasis': ['Cirujano general'],
  'Fracturas de cadera': ['Traumatólogo', 'Ortopedista'],
  'Deseo sexual inhibido': ['Sexólogo', 'Psicólogo'],
  'Abuso sexual': ['Psicólogo', 'Psiquiatra'],
  'Osteoartritis': ['Reumatólogo', 'Ortopedista'],
  'Glomerulonefritis': ['Nefrólogo'],
  'Infección urinaria en adultos': ['Urólogo', 'Internista'],
  'Fisura anal': ['Proctólogo'],
  'Muelas del juicio': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Intolerancia a la lactosa': ['Gastroenterólogo', 'Nutriólogo clínico'],
  'Trastorno de alimentación en la lactancia y en la primera infancia': ['Pediatra', 'Nutriólogo clínico'],
  'Aneurisma cerebral': ['Neurocirujano'],
  'Síndrome del colon irritable (IBS)': ['Gastroenterólogo'],
  'Tabaquismo': ['Psicólogo', 'Neumólogo'],
  'Gigantomastia': ['Cirujano plástico'],
  'Prolapso uterino': ['Ginecólogo'],
  'Bocio': ['Endocrinólogo'],
  'Celulitis': ['Dermatólogo', 'Cirujano plástico'],
  'Parálisis facial': ['Neurólogo', 'Fisioterapeuta'],
  'Bulímia': ['Psiquiatra', 'Psicólogo', 'Nutriólogo clínico'],
  'Derrame pleural': ['Neumólogo'],
  'Hipertensión inducida por el embarazo': ['Ginecólogo'],
  'Hipoacusia relacionada con la edad': ['Otorrinolaringólogo', 'Audiólogo'],
  'Fatiga crónica': ['Internista', 'Psicólogo'],
  'Aflicción': ['Psicólogo'],
  'Anomalía dentaria': ['Dentista - Odontólogo'],
  'Trastorno por atracón': ['Psicólogo', 'Psiquiatra'],
  'Trastornos cardiovasculares': ['Cardiólogo'],
  'Hidrocefalia': ['Neurocirujano'],
  'Displasia cervical': ['Ginecólogo'],
  'Epicondilitis humeral': ['Traumatólogo', 'Fisioterapeuta'],
  'Apnea del sueño': ['Neumólogo', 'Otorrinolaringólogo'],
  'Dermatitis seborreica': ['Dermatólogo'],
  'Enfermedades de la tiroides': ['Endocrinólogo'],
  'Artrosis': ['Reumatólogo', 'Ortopedista'],
  'Esguince': ['Traumatólogo'],
  'Dolor de espalda inespecífico': ['Ortopedista', 'Fisioterapeuta'],
  'Verrugas genitales': ['Ginecólogo', 'Urólogo', 'Dermatólogo'],
  'Alergia a las proteínas de la leche (niño pequeño)': ['Pediatra', 'Alergólogo'],
  'Gastroenteritis bacteriana con diarrea infecciosa': ['Gastroenterólogo', 'Infectólogo'],
  'Cicatrices de acné': ['Dermatólogo', 'Médico estético'],
  'Lupus': ['Reumatólogo'],
  'Artritis': ['Reumatólogo'],
  'Enfermedad inflamatoria pélvica (EIP)': ['Ginecólogo'],
  'Degeneración macular relacionada con la edad (AMD)': ['Oftalmólogo'],
  'Trastorno del espectro autista (TEA)': ['Neurólogo pediatra', 'Psiquiatra infantil', 'Psicólogo'],
  'Cáncer del estómago': ['Gastroenterólogo', 'Cirujano oncólogo'],
  'Falla renal crónica': ['Nefrólogo'],
  'Esterilidad': ['Ginecólogo', 'Urólogo'],
  'Condiloma acuminado': ['Urólogo', 'Ginecólogo', 'Dermatólogo'],
  'Resistencia a la insulina': ['Endocrinólogo'],
  'Estrabismo': ['Oftalmólogo'],
  'Trastorno bipolar afectivo': ['Psiquiatra'],
  'Apatía sexual': ['Sexólogo', 'Psicólogo'],
  'Acné vulgar': ['Dermatólogo'],
  'Trastornos del sueño en personas mayores': ['Geriatra', 'Neurólogo'],
  'Desgaste de rodilla': ['Ortopedista', 'Traumatólogo'],
  'Labio leporino y paladar hendido': ['Cirujano plástico', 'Cirujano maxilofacial'],
  'Traumatismo facial': ['Cirujano maxilofacial', 'Cirujano plástico'],
  'EPOC': ['Neumólogo'],
  'Cistitis aguda': ['Urólogo', 'Internista'],
  'Dislexia': ['Psicopedagogo', 'Psicólogo'],
  'Enfermedad fibroquística de las mamas': ['Ginecólogo'],
  'Enfermedades gastrointestinales': ['Gastroenterólogo'],
  'Envejecimiento cutáneo': ['Dermatólogo', 'Médico estético'],
  'Escoliosis': ['Ortopedista'],
  'Ictericia del recién nacido': ['Neonatólogo', 'Pediatra'],
  'Compresión de la médula espinal': ['Neurocirujano', 'Ortopedista'],
  'Disco roto': ['Neurocirujano', 'Traumatólogo'],
  'Deshidratación': ['Médico general', 'Urgenciólogo'],
  'Blefaritis': ['Oftalmólogo'],
  'Dolor post endodoncia': ['Dentista - Odontólogo'],
  'Dolor oncológico': ['Algólogo', 'Oncólogo médico'],
  'Cáncer de testículos': ['Urólogo', 'Oncólogo médico'],
  'Masas cutáneas de grasa': ['Dermatólogo', 'Cirujano plástico'],
  'Presión arterial alta (Hipertensión)': ['Cardiólogo', 'Internista'],
  'Enuresis': ['Pediatra', 'Urólogo'],
  'Amelogénesis imperfecta': ['Dentista - Odontólogo'],
  'Criptorquidia': ['Urólogo', 'Cirujano pediátrico'],
  'Cardiopatía congénita': ['Cardiólogo pediátrico'],
  'Hidrocele': ['Urólogo'],
  'Autismo': ['Neurólogo pediatra', 'Psiquiatra infantil'],
  'Trombosis venosa profunda': ['Angiólogo'],
  'Dolor en la espalda': ['Ortopedista', 'Fisioterapeuta'],
  'Avulsión dental': ['Dentista - Odontólogo'],
  'Parálisis cerebral': ['Neurólogo pediatra', 'Fisioterapeuta'],
  'Fractura coronal': ['Dentista - Odontólogo'],
  'Obstrucción intestinal': ['Cirujano general'],
  'Espondilitis anquilosante': ['Reumatólogo'],
  'Insuficiencia arterial': ['Angiólogo'],
  'Nódulo tiroideo': ['Endocrinólogo'],
  'Trastorno depresivo grave': ['Psiquiatra'],
  'Esclerosis múltiple': ['Neurólogo'],
  'Síndrome nefrótico': ['Nefrólogo'],
  'Enfermedad renal': ['Nefrólogo'],
  'Abuso sexual infantil': ['Psicólogo', 'Psiquiatra infantil'],
  'Quemaduras': ['Cirujano plástico', 'Médico general'],
  'Adenoides agrandadas': ['Otorrinolaringólogo'],
  'Cáncer de piel en célula basal': ['Dermatólogo', 'Cirujano oncólogo'],
  'Cistitis': ['Urólogo'],
  'Síndrome de dolor miofascial': ['Fisioterapeuta', 'Algólogo'],
  'Síndrome de caídas': ['Geriatra', 'Fisioterapeuta'],
  'Lesiones ligamentarias en mano y muñeca': ['Cirujano de la mano', 'Traumatólogo'],
  'Nefritis lúpica': ['Nefrólogo', 'Reumatólogo'],
  'Rechazo al trasplante': ['Nefrólogo', 'Inmunólogo'],
  'Trastorno límite de la personalidad': ['Psiquiatra', 'Psicólogo'],
  'Alergias a fármacos': ['Alergólogo'],
  'Tuberculosis pulmonar': ['Infectólogo', 'Neumólogo'],
  'Fibrosis pulmonar': ['Neumólogo'],
  'Síndrome de Sjogren': ['Reumatólogo'],
  'Ojo rojo': ['Oftalmólogo'],
  'Comportamiento psicótico': ['Psiquiatra'],
  'Amenorrea primaria': ['Ginecólogo'],
  'Venas varicosas': ['Angiólogo'],
  'Linfoma de Hodgkin': ['Hematólogo', 'Oncólogo médico'],
  'Dermatomiositis': ['Reumatólogo', 'Dermatólogo'],
  'Enfermedad de Meniere': ['Otorrinolaringólogo'],
  'Acalasia': ['Gastroenterólogo'],
  'Alta miopía': ['Oftalmólogo'],
  'Infección aguda del oído': ['Otorrinolaringólogo'],
  'Esofagitis': ['Gastroenterólogo'],
  'Trastorno de identidad de género': ['Psicólogo', 'Sexólogo', 'Psiquiatra'],
  'Cuello torcido': ['Traumatólogo', 'Fisioterapeuta'],
  'Trauma ocular': ['Oftalmólogo'],
  'Melanoma': ['Dermatólogo', 'Cirujano oncólogo'],
  'Erosión Dental': ['Dentista - Odontólogo'],
  'Derrame cerebral': ['Neurólogo', 'Neurocirujano'],
  'Adenomiosis': ['Ginecólogo'],
  'Trastorno del sueño por ansiedad': ['Psiquiatra', 'Psicólogo'],
  'Absceso anal': ['Proctólogo'],
  'Enfermedad celíaca (esprúe)': ['Gastroenterólogo'],
  'Insuficiencia renal aguda': ['Nefrólogo'],
  'Cerumen (cera del oído)': ['Otorrinolaringólogo'],
  'Cáncer de cabeza y cuello': ['Cirujano oncólogo', 'Otorrinolaringólogo'],
  'Intolerancia al gluten': ['Gastroenterólogo', 'Nutriólogo clínico'],
  'Juanetes': ['Ortopedista', 'Podólogo'],
  'Infección del oído': ['Otorrinolaringólogo'],
  'Presbicia': ['Oftalmólogo'],
  'Fistula dental o en encía': ['Dentista - Odontólogo'],
  'Hipercolesterolemia familiar': ['Endocrinólogo', 'Genetista', 'Internista'],
  'Espondiloartropatía': ['Reumatólogo'],
  'Insuficiencia renal': ['Nefrólogo'],
  'Insuficiencia aguda del riñón': ['Nefrólogo'],
  'Enfermedad renal terminal': ['Nefrólogo'],
  'Tenosinovitis': ['Traumatólogo', 'Fisioterapeuta'],
  'Enfermedad inflamatoria intestinal': ['Gastroenterólogo'],
  'Dislalia': ['Logopeda'],
  'Bursitis epitroclear': ['Traumatólogo'],
  'Amenorrea secundaria': ['Ginecólogo'],
  'Infarto cerebral': ['Neurólogo'],
  'Cáncer de endometrio': ['Ginecólogo oncológico'],
  'Insuficiencia crónica del riñón': ['Nefrólogo'],
  'Mieloma múltiple': ['Hematólogo'],
  'Nariz bulbosa': ['Dermatólogo', 'Cirujano plástico'],
  'Control de emociones': ['Psicólogo'],
  'Pancreatitis aguda': ['Gastroenterólogo', 'Cirujano general'],
  'Accidente cerebrovascular isquémico': ['Neurólogo'],
  'Inestabilidad Glenohumeral': ['Traumatólogo'],
  'Litiasis renal': ['Urólogo'],
  'Insomnio crónico': ['Psiquiatra', 'Psicólogo'],
  'Taquicardia': ['Cardiólogo'],
  'Leucemia': ['Hematólogo', 'Oncólogo médico'],
  'Drogadicción': ['Psiquiatra', 'Psicólogo'],
  'Acidez': ['Gastroenterólogo'],
  'Contractura de Dupuytren': ['Cirujano de la mano'],
  'Insuficiencia venosa crónica': ['Angiólogo'],
  'Hipoacusia en bebés': ['Audiólogo', 'Otorrinolaringólogo'],
  'Trastornos en la alimentación del anciano': ['Geriatra', 'Nutriólogo clínico'],
  'Lesión cerebral en bebés': ['Neurólogo pediatra', 'Neonatólogo'],
  'Artritis psoriásica': ['Reumatólogo', 'Dermatólogo'],
  'Linfoma no Hodgkin': ['Hematólogo', 'Oncólogo médico'],
  'Ausencia de la menstruación': ['Ginecólogo'],
  'Infección aguda de las vías urinarias (IVU aguda)': ['Urólogo'],
  'Orzuelo': ['Oftalmólogo'],
  'Dentición': ['Odontólogo pediatra'],
  'Hipertensión pulmonar': ['Cardiólogo', 'Neumólogo'],
  'Trastornos de la voz': ['Logopeda', 'Otorrinolaringólogo'],
  'Parálisis espástica': ['Neurólogo', 'Fisioterapeuta'],
  'Pinzamiento Subacromial': ['Traumatólogo'],
  'Trastornos por inmunodeficiencia': ['Inmunólogo'],
  'Niveles elevados de colesterol y triglicéridos': ['Internista', 'Endocrinólogo'],
  'Estenosis aórtica': ['Cardiólogo'],
  'Hipotiroidismo en adultos': ['Endocrinólogo'],
  'Síndrome de dificultad respiratoria en neonatos': ['Neonatólogo'],
  'Síndrome del túnel carpiano': ['Cirujano de la mano', 'Fisioterapeuta'],
  'Atrofia muscular espinal': ['Neurólogo'],
  'Trastornos asociados con el vértigo': ['Otorrinolaringólogo'],
  'Bronconeumonía': ['Neumólogo', 'Pediatra'],
  'Tumor cerebral en niños': ['Neurocirujano', 'Oncólogo pediátrico'],
  'Degeneración macular': ['Oftalmólogo'],
  'Agujero macular': ['Oftalmólogo'],
  'Aneurisma': ['Angiólogo', 'Neurocirujano'],
  'Asimetría facial': ['Cirujano maxilofacial', 'Cirujano plástico'],
  'Herpes zóster (culebrilla)': ['Dermatólogo', 'Infectólogo'],
  'Abuso del alcohol': ['Psiquiatra', 'Psicólogo'],
  'Esclerodermia': ['Reumatólogo'],
  'Falta de fluidez en el lenguaje': ['Logopeda'],
  'Insomnio psicofisiológico (aprendido)': ['Psicólogo'],
  'Fluorosis': ['Dentista - Odontólogo'],
  'Miastenia grave': ['Neurólogo'],
  'Coágulo en las piernas': ['Angiólogo'],
  'Adherencias': ['Cirujano general'],
  'Coagulopatía': ['Hematólogo'],
  'Psicosis': ['Psiquiatra'],
  'Estenosis pilórica': ['Cirujano pediátrico'],
  'Dolor de rodilla': ['Traumatólogo', 'Fisioterapeuta'],
  'Púrpura trombocitopénica idiopática (ITP)': ['Hematólogo'],
  'Postura jorobada': ['Ortopedista', 'Fisioterapeuta'],
  'Tapón de cerumen': ['Otorrinolaringólogo'],
  'Violencia de género': ['Psicólogo'],
  'Varicela': ['Pediatra'],
  'Queratoglobo': ['Oftalmólogo'],
  'Accidente cerebrovascular': ['Neurólogo'],
  'Úlcera gastroduodenal aguda': ['Gastroenterólogo'],
  'Rodilla vara': ['Ortopedista'],
  'Dependencia del alcohol': ['Psiquiatra', 'Psicólogo'],
  'Gota aguda': ['Reumatólogo'],
  'Absceso del ano y el recto': ['Proctólogo'],
  'Enfermedades y dolor crónico': ['Algólogo'],
  'Rosácea': ['Dermatólogo'],
  'Pie equino varo': ['Ortopedista'],
  'Enfermedades renales': ['Nefrólogo'],
  'Trastornos de lenguaje': ['Logopeda', 'Psicopedagogo'],
  'Agrandamiento de la próstata': ['Urólogo'],
  'Síndrome de Down': ['Genetista', 'Pediatra'],
  'Convulsiones febriles': ['Pediatra', 'Neurólogo pediatra'],
  'Divertículo de Meckel': ['Cirujano pediátrico'],
  'Traumatismo dental': ['Dentista - Odontólogo'],
  'Cáncer': ['Oncólogo médico'],
  'Dolor de cabeza': ['Médico general', 'Neurólogo'],
  'Úlceras e infecciones corneales': ['Oftalmólogo'],
  'Cervicitis': ['Ginecólogo'],
  'Flebitis': ['Angiólogo'],
  'Crisis respiratoria en recién nacidos': ['Neonatólogo'],
  'Fimosis': ['Urólogo', 'Cirujano pediátrico'],
  'Bursitis retrocalcánea': ['Traumatólogo'],
  'Osteoporosis por Climaterio': ['Ginecólogo', 'Endocrinólogo'],
  'Tristeza': ['Psicólogo'],
  'Ronquido': ['Otorrinolaringólogo', 'Neumólogo'],
  'Dependencia emocional': ['Psicólogo'],
  'Trastornos de las glándulas salivales': ['Otorrinolaringólogo'],
  'Fibroadenoma de mama': ['Ginecólogo'],
  'Reducción de grasa (adiposidades)': ['Cirujano plástico', 'Especialista en Obesidad y Delgadez'],
  'Anemia ferropénica en niños': ['Pediatra', 'Hematólogo pediatra'],
  'Cardiopatías': ['Cardiólogo'],
  'Dermatitis por contacto': ['Dermatólogo'],
  'Demencia vascular': ['Geriatra', 'Neurólogo'],
  'Deseo sexual hipoactivo': ['Sexólogo'],
  'Aversión al sexo': ['Sexólogo', 'Psicólogo'],
  'Insuficiencia venosa': ['Angiólogo'],
  'Pérdida auditiva relacionada con la edad': ['Audiólogo', 'Otorrinolaringólogo'],
  'Cardiomiopatía dilatada': ['Cardiólogo'],
  'Tumores o protuberancias en las mamas': ['Ginecólogo', 'Cirujano oncólogo'],
  'Dedos en garra': ['Ortopedista', 'Podólogo'],
  'Anemia por deficiencia de hierro en los niños': ['Pediatra', 'Hematólogo pediatra'],
  'Estreñimiento en niños': ['Pediatra', 'Gastroenterólogo pediátrico'],
  'Influenza': ['Médico de familia', 'Infectólogo'],
  'Cifoescoliosis': ['Ortopedista'],
  'Estenosis mitral': ['Cardiólogo'],
  'Enfermedad cerebrovascular': ['Neurólogo'],
  'Trombocitopenia': ['Hematólogo'],
  'Alopecia en hombres': ['Dermatólogo'],
  'Absceso de Bartolino': ['Ginecólogo'],
  'Trastorno de oposición desafiante': ['Psiquiatra infantil', 'Psicólogo'],
  'Uveítis': ['Oftalmólogo'],
  'Edema macular': ['Oftalmólogo'],
  'Atresia esofágica': ['Cirujano pediátrico'],
  'Peritonitis': ['Cirujano general'],
  'Angina inestable': ['Cardiólogo'],
  'Colitis ulcerosa': ['Gastroenterólogo'],
  'Tumor nasal': ['Otorrinolaringólogo'],
  'Abuso de drogas y farmacodependencia': ['Psiquiatra', 'Psicólogo'],
  'Dolor de nervio o dolor nervioso': ['Algólogo', 'Neurólogo'],
  'Trastornos hormonales': ['Endocrinólogo'],
  'Retraso del desarrollo': ['Pediatra', 'Neurólogo pediatra'],
  'Amenaza de aborto espontáneo': ['Ginecólogo'],
  'Malabsorción': ['Gastroenterólogo'],
  'Trastorno del desarrollo de la lectura': ['Psicopedagogo'],
  'Discapacidad intelectual': ['Psiquiatra infantil', 'Psicopedagogo'],
  'Enfermedad vascular periférica': ['Angiólogo'],
  'Incontinencia fecal': ['Proctólogo', 'Gastroenterólogo'],
  'Parálisis del nervio facial': ['Neurólogo', 'Fisioterapeuta'],
  'Celiaquía': ['Gastroenterólogo'],
  'Fractura de la pelvis': ['Traumatólogo'],
  'Ambliopía': ['Oftalmólogo'],
  'Síndrome de dolor regional complejo': ['Algólogo', 'Fisioterapeuta'],
  'Hemofilia': ['Hematólogo'],
  'Síndrome del intestino corto': ['Gastroenterólogo'],
  'Infección crónica de los senos paranasales': ['Otorrinolaringólogo'],
  'Síncope': ['Cardiólogo', 'Neurólogo'],
  'Fractura de antebrazo': ['Traumatólogo'],
  'Obesidad infantil': ['Pediatra', 'Endocrinólogo pediátrico', 'Nutriólogo clínico'],
  'Aborto incompleto': ['Ginecólogo'],
  'Agrandamiento de adenoides': ['Otorrinolaringólogo'],
  'Hidrocele de la túnica vaginal del testículo (proceso vaginal)': ['Urólogo'],
  'Gingivitis ulceronecrosante aguda': ['Dentista - Odontólogo'],
  'Estenosis de la válvula aórtica': ['Cardiólogo'],
  'Dolor somático': ['Algólogo', 'Psicólogo'],
  'Adherencia intraperitoneal': ['Cirujano general'],
  'Candidiasis vaginal': ['Ginecólogo'],
  'Infección de las vías urinarias (IVU) en adultos': ['Urólogo', 'Internista'],
  'El tartamudeo y los niños': ['Logopeda'],
  'Cálculos en el tracto urinario': ['Urólogo'],
  'Ano imperforado': ['Cirujano pediátrico'],
  'Neuronitis vestibular': ['Otorrinolaringólogo'],
  'Falla cardíaca': ['Cardiólogo'],
  'Dedo del pie en martillo': ['Ortopedista', 'Podólogo'],
  'Hipocondría': ['Psicólogo', 'Psiquiatra'],
  'Desregulación disruptiva del estado de ánimo': ['Psiquiatra infantil', 'Psicólogo'],
  'Trastorno de pánico con agorafobia': ['Psiquiatra', 'Psicólogo'],
  'Obstrucción del conducto lagrimal': ['Oftalmólogo'],
  'Capsulitis adhesiva': ['Fisioterapeuta', 'Traumatólogo'],
  'Sordera': ['Audiólogo', 'Otorrinolaringólogo'],
  'Dolor terminal': ['Algólogo'],
  'Síndrome del intestino irritable': ['Gastroenterólogo'],
  'Hiperhidrosis': ['Dermatólogo'],
  'Displasia del desarrollo de la cadera': ['Ortopedista'],
  'Lesión corneal': ['Oftalmólogo'],
  'Absceso periamigdalino': ['Otorrinolaringólogo'],
  'Gastrosquisis': ['Cirujano pediátrico'],
  'Cáncer del páncreas': ['Cirujano oncólogo', 'Gastroenterólogo'],
  'Mucocele': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Cervicalgía': ['Fisioterapeuta', 'Ortopedista'],
  'Vulvovaginitis': ['Ginecólogo'],
  'Colesterol': ['Internista', 'Nutriólogo clínico'],
  'Ascitis': ['Gastroenterólogo', 'Internista'],
  'Neuropatía diabética': ['Endocrinólogo', 'Neurólogo'],
  'Cáncer bucal': ['Cirujano oncólogo', 'Dentista - Odontólogo'],
  'Onicomicosis': ['Podólogo', 'Dermatólogo'],
  'Perimenopausia': ['Ginecólogo'],
  'Distrofia muscular': ['Neurólogo'],
  'Parto prematuro': ['Ginecólogo', 'Neonatólogo'],
  'Alcoholismo': ['Psiquiatra', 'Psicólogo'],
  'Ateroesclerosis': ['Cardiólogo', 'Angiólogo'],
  'Miocardiopatías': ['Cardiólogo'],
  'Prolapso rectal': ['Proctólogo'],
  'Adenoma de tiroides': ['Endocrinólogo'],
  'Piedras en el riñón': ['Urólogo'],
  'Caspa': ['Dermatólogo'],
  'Angina crónica': ['Cardiólogo'],
  'Linfedema': ['Angiólogo', 'Fisioterapeuta'],
  'Cáncer de vejiga': ['Urólogo', 'Oncólogo médico'],
  'Cáncer de pene': ['Urólogo', 'Oncólogo médico'],
  'Fibrosis quística': ['Neumólogo', 'Pediatra'],
  'Crup': ['Pediatra'],
  'Arrancamiento compulsivo del cabello': ['Psiquiatra', 'Psicólogo'],
  'Verrugas del pene': ['Urólogo', 'Dermatólogo'],
  'Fractura de fémur': ['Traumatólogo'],
  'Síndrome de resistencia a la insulina': ['Endocrinólogo'],
  'Acné rosácea': ['Dermatólogo'],
  'Pubertad precoz': ['Endocrinólogo pediátrico'],
  'Retraso en el desarrollo psicomotor': ['Pediatra', 'Neurólogo pediatra'],
  'Infección urinaria recurrente': ['Urólogo'],
  'Accidente cerebrovascular hemorrágico': ['Neurólogo', 'Neurocirujano'],
  'Diplopía (visión doble)': ['Oftalmólogo'],
  'Hematoma epidural': ['Neurocirujano'],
  'Miedos y fobias': ['Psicólogo'],
  'Comunicación interauricular': ['Cardiólogo pediátrico', 'Cardiólogo'],
  'Cáncer endometrial': ['Ginecólogo oncológico'],
  'Delirium': ['Geriatra', 'Psiquiatra'],
  'Balanitis': ['Urólogo', 'Dermatólogo'],
  'Conducta': ['Psicólogo', 'Psiquiatra'],
  'Úlceras venosas': ['Angiólogo', 'Dermatólogo'],
  'Codo de niñera': ['Traumatólogo', 'Pediatra'],
  'Aborto espontáneo': ['Ginecólogo'],
  'Trastornos del desarrollo sexual': ['Endocrinólogo', 'Genetista', 'Ginecólogo'],
  'Enfermedad de Osgood-Schlatter': ['Ortopedista', 'Traumatólogo'],
  'Hiperplasia prostática': ['Urólogo'],
  'Oclusión de las venas retinianas': ['Oftalmólogo'],
  'Laberíntitis': ['Otorrinolaringólogo', 'Audiólogo'],
  'Hiperparatiroidismo': ['Endocrinólogo'],
  'Cálculo en el conducto biliar': ['Gastroenterólogo', 'Cirujano general'],
  'Quiste sebáceo': ['Dermatólogo', 'Cirujano general'],
  'Artritis gotosa aguda': ['Reumatólogo'],
  'Craneosinostosis': ['Neurocirujano', 'Cirujano pediátrico'],
  'Mastopatia fibroquística': ['Ginecólogo'],
  'Subluxación vertebral': ['Traumatólogo', 'Fisioterapeuta'],
  'Restricción del crecimiento intrauterino': ['Ginecólogo'],
  'Ludopatía': ['Psicólogo', 'Psiquiatra'],
  'Afecciones asociadas con la ictericia': ['Gastroenterólogo', 'Internista'],
  'Úlcera péptica': ['Gastroenterólogo'],
  'Defensas bajas': ['Inmunólogo', 'Internista'],
  'Síndrome de apnea obstructiva del sueño': ['Neumólogo', 'Otorrinolaringólogo'],
  'Lesiones de Lefort': ['Cirujano maxilofacial'],
  'Molusco contagioso': ['Dermatólogo'],
  'Embarazo abdominal': ['Ginecólogo'],
  'Tos crónica': ['Neumólogo', 'Internista'],
  'Angina estable': ['Cardiólogo'],
  'Colangitis': ['Gastroenterólogo', 'Cirujano general'],
  'Infección recurrente de las vías urinarias': ['Urólogo'],
  'Displasia congénita de la cadera': ['Ortopedista'],
  'Encefalopatía hepática': ['Gastroenterólogo'],
  'Enfermedad ovárica poliquística': ['Ginecólogo', 'Endocrinólogo'],
  'TEPT': ['Psicólogo', 'Psiquiatra'],
  'Trauma': ['Traumatólogo', 'Urgenciólogo'],
  'Esclerosis sistémica': ['Reumatólogo'],
  'Trastorno de personalidad narcisista': ['Psicólogo', 'Psiquiatra'],
  'Lesión maxilofacial': ['Cirujano maxilofacial'],
  'Pericarditis': ['Cardiólogo'],
  'Síndrome de dolor pélvico': ['Ginecólogo', 'Urólogo'],
  'Ataque cardíaco': ['Cardiólogo', 'Urgenciólogo'],
  'Fibromiositis': ['Reumatólogo', 'Fisioterapeuta'],
  'Cetoacidosis diabética': ['Endocrinólogo', 'Internista'],
  'Embarazo de bajo riesgo': ['Ginecólogo'],
  'Cáncer de útero': ['Ginecólogo oncológico'],
  'TAG': ['Psicólogo', 'Psiquiatra'],
  'Nefrolitiasis': ['Urólogo', 'Nefrólogo'],
  'Sinusitis crónica': ['Otorrinolaringólogo'],
  'Cáncer de piel escamocelular': ['Dermatólogo', 'Cirujano oncólogo'],
  'Adenomioma': ['Ginecólogo'],
  'Malformación anorrectal': ['Cirujano pediátrico'],
  'Cardiopatía coronaria': ['Cardiólogo'],
  'Infección del riñón': ['Nefrólogo', 'Urólogo'],
  'Deficiencia de la hormona del crecimiento': ['Endocrinólogo'],
  'Infección por VIH': ['Infectólogo'],
  'Congoja': ['Psicólogo'],
  'Lesiones ligamentarias de rodillas': ['Traumatólogo', 'Ortopedista'],
  'Enfermedades terminales': ['Geriatra', 'Internista', 'Algólogo'],
  'Enfermedad de von Willebrand': ['Hematólogo'],
  'Malformación arteriovenosa cerebral': ['Neurocirujano'],
  'Hematoma subdural crónico': ['Neurocirujano'],
  'Absceso de las amígdalas': ['Otorrinolaringólogo'],
  'Trastorno de la personalidad esquizoide': ['Psiquiatra', 'Psicólogo'],
  'Relaciones insanas': ['Psicólogo'],
  'Trastornos de la marcha': ['Geriatra', 'Neurólogo', 'Fisioterapeuta'],
  'Nevos': ['Dermatólogo'],
  'Enfermedad de Legg-Calve-Perthes': ['Ortopedista'],
  'Visión baja': ['Oftalmólogo', 'Optometrista'],
  'Cáncer del hígado': ['Gastroenterólogo', 'Cirujano oncólogo'],
  'Hipospadias': ['Urólogo', 'Cirujano pediátrico'],
  'Síndrome de distrofia simpática refleja': ['Algólogo', 'Fisioterapeuta'],
  'Deformidad en valgo del dedo gordo': ['Ortopedista', 'Podólogo'],
  'Miedo': ['Psicólogo'],
  'Delirio': ['Psiquiatra', 'Geriatra'],
  'Encopresis': ['Pediatra', 'Psicólogo infantil'],
  'Inseguridad': ['Psicólogo'],
  'Alergia al moho, la caspa y el polvo': ['Alergólogo'],
  'Aneurisma aórtico': ['Angiólogo', 'Cirujano cardiovascular y torácico'],
  'Accidente cardiovascular': ['Neurólogo', 'Cardiólogo'],
  'Diarrea crónica': ['Gastroenterólogo'],
  'Cambios en la piel inducidos por el sol': ['Dermatólogo'],
  'Deficiencia de vitamina D': ['Endocrinólogo', 'Internista'],
  'Hombro doloroso': ['Traumatólogo', 'Fisioterapeuta'],
  'Cefalea en racimo': ['Neurólogo'],
  'Peritonitis asociada con diálisis': ['Nefrólogo'],
  'Párpados caídos': ['Oftalmólogo', 'Cirujano plástico'],
  'Lesión renal aguda': ['Nefrólogo'],
  'Meningioma en adultos': ['Neurocirujano'],
  'Personalidad psicopática': ['Psiquiatra', 'Psicólogo'],
  'Neuralgia glosofaríngea': ['Neurólogo'],
  'Alergias a las mascotas': ['Alergólogo'],
  'Comunicación interventricular': ['Cardiólogo pediátrico'],
  'Úlcera gástrica': ['Gastroenterólogo'],
  'Queratosis: tumores benignos de la piel': ['Dermatólogo'],
  'Espondilitis': ['Reumatólogo', 'Ortopedista'],
  'Calvicie de patrón masculino': ['Dermatólogo'],
  'Gestión de emociones': ['Psicólogo'],
  'Infección complicada de las vías urinarias': ['Urólogo', 'Infectólogo'],
  'Deficiencia articulatoria': ['Logopeda'],
  'Trastorno fonológico': ['Logopeda'],
  'Gingivoestomatitis': ['Odontólogo pediatra', 'Pediatra'],
  'Hepatitis C': ['Gastroenterólogo', 'Infectólogo'],
  'Dermatitis y úlceras por estasis': ['Angiólogo', 'Dermatólogo'],
  'Celotipia': ['Psicólogo', 'Psiquiatra'],
  'Infertilidad masculina': ['Urólogo'],
  'Bacteriuria asintomática': ['Urólogo', 'Internista'],
  'Hombro de tenista': ['Traumatólogo', 'Fisioterapeuta'],
  'Displasia broncopulmonar': ['Neumólogo pediatra', 'Neonatólogo'],
  'Sonrisa gingival': ['Odontólogo', 'Cirujano maxilofacial'],
  'Desviación Septal': ['Otorrinolaringólogo'],
  'Enfermedad de Crohn': ['Gastroenterólogo'],
  'Cáncer laríngeo': ['Otorrinolaringólogo', 'Cirujano oncólogo'],
  'Hipoglucemia': ['Endocrinólogo'],
  'Aborto electivo o terapéutico': ['Ginecólogo'],
  'Hiperlordosis': ['Ortopedista', 'Fisioterapeuta'],
  'Hombro de nadador': ['Traumatólogo', 'Fisioterapeuta'],
  'Artritis por gota crónica': ['Reumatólogo'],
  'Tumor de la médula espinal': ['Neurocirujano'],
  'Trastorno de pánico': ['Psicólogo', 'Psiquiatra'],
  'Enfermedad de Hirschsprung': ['Cirujano pediátrico'],
  'Arterioesclerosis': ['Cardiólogo', 'Angiólogo'],
  'Dolor de hombro': ['Traumatólogo', 'Fisioterapeuta'],
  'Hernia crural': ['Cirujano general'],
  'Infecciones frecuentes de garganta': ['Otorrinolaringólogo'],
  'Acalasia esofágica': ['Gastroenterólogo', 'Cirujano general'],
  'Reflujo vesicoureteral': ['Urólogo pediátrico', 'Nefrólogo pediatra'],
  'Insuficiencia en el crecimiento': ['Endocrinólogo pediátrico', 'Pediatra'],
  'Diarrea bacteriana': ['Gastroenterólogo', 'Infectólogo'],
  'Leiomioma': ['Ginecólogo'],
  'Infección urinaria complicada': ['Urólogo'],
  'Trastorno Déficit de atención e hiperactividad': ['Neurólogo pediatra', 'Psiquiatra infantil'],
  'Nutrición y salud emocional': ['Psicólogo', 'Nutriólogo clínico'],
  'Ptosis': ['Oftalmólogo'],
  'Tumor cerebral canceroso (metastásico)': ['Neurocirujano', 'Oncólogo médico'],
  'Acumulación de placa en las arterias': ['Cardiólogo', 'Angiólogo'],
  'Almorranas': ['Proctólogo'],
  'Lipoma cervical': ['Cirujano general', 'Dermatólogo'],
  'Asma inducido por el ejercicio': ['Neumólogo', 'Alergólogo'],
  'Enfermedad cardíaca isquémica': ['Cardiólogo'],
  'Tartamudeo': ['Logopeda'],
  'Blefaroespasmo': ['Oftalmólogo', 'Neurólogo'],
  'Diverticulosis': ['Gastroenterólogo'],
  'Neoplasia intraepitelial cervical': ['Ginecólogo oncológico'],
  'Ectropión': ['Oftalmólogo'],
  'Neuropatía del nervio ciático': ['Neurólogo', 'Traumatólogo'],
  'Daño renal': ['Nefrólogo'],
  'Absceso cerebral': ['Neurocirujano', 'Infectólogo'],
  'Gastritis crónica': ['Gastroenterólogo'],
  'Neumotórax': ['Cirujano cardiovascular y torácico', 'Neumólogo'],
  'Neuralgia del trigémino': ['Neurólogo', 'Neurocirujano'],
  'Exceso de flujo vaginal - leucorrea': ['Ginecólogo'],
  'Calvicie de patrón femenino': ['Dermatólogo'],
  'Temblor inducido por fármacos': ['Neurólogo', 'Psiquiatra'],
  'Patologías del crecimiento': ['Endocrinólogo pediátrico'],
  'Hipotiroidismo congénito': ['Endocrinólogo pediátrico', 'Neonatólogo'],
  'Adherencia pélvica': ['Ginecólogo', 'Cirujano general'],
  'Pesadillas constantes': ['Psicólogo', 'Psiquiatra'],
  'Cifosis': ['Ortopedista', 'Fisioterapeuta'],
  'Tumor del riñón o Tumor renal': ['Urólogo', 'Cirujano oncólogo'],
  'Atresia duodenal': ['Cirujano pediátrico'],
  'Enfermedad coronaria (CHD)': ['Cardiólogo'],
  'Fístula gastrointestinal': ['Gastroenterólogo', 'Cirujano general'],
  'Ronchas o habones': ['Alergólogo', 'Dermatólogo'],
  'Cardiopatía cianótica': ['Cardiólogo pediátrico'],
  'Bocio multinodular tóxico': ['Endocrinólogo'],
  'Adenoma hipofisario secretor de prolactina': ['Endocrinólogo', 'Neurocirujano'],
  'Hiperplasia suprarrenal congénita': ['Endocrinólogo pediátrico', 'Genetista'],
  'Parálisis de Erb-Duchenne': ['Neurólogo pediatra', 'Fisioterapeuta'],
  'Síndrome de Williams': ['Genetista', 'Cardiólogo pediátrico'],
  'Espasticidad': ['Neurólogo', 'Fisioterapeuta'],
  'Adenoma secretante': ['Endocrinólogo'],
  'Mioma': ['Ginecólogo'],
  'Eclampsia': ['Ginecólogo'],
  'Trastorno esquizoafectivo': ['Psiquiatra'],
  'Estenosis raquídea': ['Ortopedista', 'Neurocirujano'],
  'Cataratas congénitas': ['Oftalmólogo pediátrico'],
  'Próstata agrandada': ['Urólogo'],
  'Infección crónica del oído': ['Otorrinolaringólogo'],
  'Sangrado nasal': ['Otorrinolaringólogo'],
  'Trastorno del control de los impulsos': ['Psicólogo', 'Psiquiatra'],
  'Dolor de columna': ['Ortopedista', 'Fisioterapeuta'],
  'Dolor de espalda': ['Ortopedista', 'Fisioterapeuta'],
  'Absceso mamario': ['Ginecólogo', 'Cirujano general'],
  'Trastorno del desarrollo del lenguaje expresivo': ['Logopeda'],
  'Ovario poliquístico': ['Ginecólogo', 'Endocrinólogo'],
  'Condromalacia rotuliana': ['Traumatólogo', 'Fisioterapeuta'],
  'Agorafobia': ['Psicólogo', 'Psiquiatra'],
  'Pielonefritis': ['Nefrólogo', 'Urólogo'],
  'Subluxación': ['Traumatólogo', 'Fisioterapeuta'],
  'Tromboflebitis': ['Angiólogo'],
  'Pólipos colorrectales': ['Gastroenterólogo', 'Proctólogo'],
  'Cáncer de esófago': ['Gastroenterólogo', 'Cirujano oncólogo'],
  'Artritis bacteriana': ['Reumatólogo', 'Infectólogo'],
  'Codo dislocado en niños': ['Traumatólogo', 'Pediatra'],
  'Tumor medular': ['Neurocirujano'],
  'Síndrome de Turner': ['Genetista', 'Endocrinólogo'],
  'Poliquistosis ovárica': ['Ginecólogo', 'Endocrinólogo'],
  'Deseo sexual hiperactivo': ['Sexólogo', 'Psicólogo'],
  'Infección viral de las vías respiratorias bajas': ['Neumólogo', 'Pediatra'],
  'Displasia del desarrollo de la articulación de la cadera': ['Ortopedista'],
  'Disfunción de la trompa de Eustaquio': ['Otorrinolaringólogo'],
  'Hernia diafragmática': ['Cirujano general', 'Cirujano pediátrico'],
  'Perforación gastrointestinal': ['Cirujano general'],
  'Dolor de cadera': ['Ortopedista', 'Traumatólogo'],
  'Absceso intraabdominal': ['Cirujano general'],
  'Laringotraqueobronquitis aguda': ['Otorrinolaringólogo', 'Pediatra'],
  'Conducto arterial persistente': ['Cardiólogo pediátrico'],
  'Estenosis uretral': ['Urólogo'],
  'Síndrome femororrotuliano': ['Traumatólogo', 'Fisioterapeuta'],
  'Cáncer de garganta': ['Otorrinolaringólogo', 'Cirujano oncólogo'],
  'Trastorno de dolor': ['Psicólogo', 'Algólogo'],
  'Amebiasis': ['Gastroenterólogo', 'Infectólogo'],
  'Eccema': ['Dermatólogo', 'Alergólogo'],
  'Riñones poliquísticos': ['Nefrólogo'],
  'Arcos caídos': ['Ortopedista', 'Podólogo'],
  'Dengue': ['Infectólogo'],
  'Afasia': ['Neurólogo', 'Logopeda'],
  'Eliminación de amalgamas': ['Dentista - Odontólogo'],
  'Periimplantitis': ['Dentista - Odontólogo'],
  'Alergia de insectos': ['Alergólogo'],
  'Gripe': ['Médico general', 'Internista'],
  'Inclusión dentaria': ['Dentista - Odontólogo', 'Cirujano maxilofacial'],
  'Hidronefrosis': ['Nefrólogo', 'Urólogo'],
  'Pie cavo': ['Ortopedista', 'Podólogo'],
  'Síndrome antifosfolípido': ['Reumatólogo', 'Hematólogo'],
  'Eyaculación retrasada en el sexo': ['Sexólogo', 'Urólogo'],
  'Espondilolistesis': ['Ortopedista', 'Neurocirujano'],
  'Temblor': ['Neurólogo'],
  'Anquiloglosia': ['Odontólogo', 'Cirujano maxilofacial'],
  'Proctitis': ['Proctólogo', 'Gastroenterólogo'],
  'Condromalacia patelar': ['Traumatólogo', 'Fisioterapeuta'],
  'Insuficiencia respiratoria': ['Neumólogo', 'Urgenciólogo'],
  'Polidactilia': ['Ortopedista', 'Cirujano pediátrico'],
  'Acromegalia': ['Endocrinólogo'],
  'Adherencia intrauterina': ['Ginecólogo'],
  'Anemia ferropénica': ['Hematólogo', 'Internista'],
  'Posmenopausia': ['Ginecólogo'],
  'Sinusitis aguda': ['Otorrinolaringólogo'],
  'Enfermedad glomerular lúpica': ['Nefrólogo', 'Reumatólogo'],
  'Osteosarcoma': ['Oncólogo médico', 'Traumatólogo'],
  'Glioma en adultos': ['Neurocirujano', 'Oncólogo médico'],
  'Aneurisma de la aorta torácica': ['Cirujano cardiovascular y torácico'],
  'Infecciones de vías respiratorias de repetición (o recurrentes)': ['Otorrinolaringólogo', 'Pediatra'],
  'Quiste pilonidal': ['Cirujano general', 'Proctólogo'],
  'Fractura de mano': ['Traumatólogo', 'Cirujano de la mano'],
  'Hepatitis autoinmunitaria': ['Gastroenterólogo'],
  'Gonartrosis': ['Ortopedista'],
  'Radiculopatía cervical': ['Traumatólogo', 'Neurocirujano'],
  'Enfisema pulmonar': ['Neumólogo'],
  'Rítides facial': ['Dermatólogo', 'Médico estético'],
  'Osteomielitis': ['Traumatólogo', 'Infectólogo'],
  'Retinopatía hipertensiva': ['Oftalmólogo', 'Cardiólogo'],
  'Trastorno de personalidad histriónica': ['Psicólogo', 'Psiquiatra'],
  'Infecciones de vías urinarias': ['Urólogo', 'Internista'],
  'Aneurisma aórtico abdominal': ['Angiólogo', 'Cirujano vascular'],
  'Dolor crónico': ['Algólogo', 'Fisioterapeuta'],
  'Tumor tiroideo': ['Endocrinólogo', 'Cirujano oncólogo'],
  'GERD': ['Gastroenterólogo'],
  'Sindactilia': ['Ortopedista', 'Cirujano plástico'],
  'Hipertensión renal': ['Nefrólogo', 'Cardiólogo'],
  'Prolactinoma': ['Endocrinólogo'],
  'Evento vascular cerebral': ['Neurólogo'],
  'Enfermedad de Cushing': ['Endocrinólogo'],
  'Corea de Huntington': ['Neurólogo'],
  'Anemia aplásica adquirida': ['Hematólogo'],
  'Desnutrición infantil': ['Pediatra', 'Nutriólogo clínico'],
  'Defectos de refracción': ['Oftalmólogo', 'Optometrista'],
  'Cáncer tiroideo (carcinoma medular)': ['Cirujano oncólogo', 'Endocrinólogo'],
  'Accidente cerebrovascular cardioembólico': ['Neurólogo', 'Cardiólogo'],
  'Alergias en ambientes interiores': ['Alergólogo'],
  'Prediabetes': ['Endocrinólogo', 'Internista'],
  'Hemangioma': ['Dermatólogo', 'Cirujano plástico'],
  'Neuropatias Compresivas': ['Traumatólogo', 'Neurólogo'],
  'Adenocarcinoma del útero': ['Ginecólogo oncológico'],
  'Bebé de madre diabética': ['Neonatólogo', 'Endocrinólogo pediátrico'],
  'Anemia hemolítica': ['Hematólogo'],
  'Cistitis en niños': ['Pediatra', 'Urólogo'],
  'Eyaculación retrasada': ['Sexólogo', 'Urólogo'],
  'Exotropía': ['Oftalmólogo'],
  'Membrana epirretiniana macular': ['Oftalmólogo'],
  'Boca de trinchera': ['Dentista - Odontólogo'],
  'Tinnitus': ['Otorrinolaringólogo', 'Audiólogo'],
  'Glaucoma de ángulo abierto': ['Oftalmólogo'],
  'Cifosis postural': ['Fisioterapeuta', 'Ortopedista'],
  'Manos entumidas': ['Neurólogo', 'Traumatólogo'],
  'Arterioesclerosis de las extremidades': ['Angiólogo', 'Cardiólogo'],
  'Soplo cardíaco': ['Cardiólogo'],
  'Embolia arterial': ['Angiólogo', 'Cardiólogo'],
  'Hipertensión renovascular': ['Nefrólogo', 'Cardiólogo'],
  'Tumor pituitario (tumor de la hipófisis)': ['Endocrinólogo', 'Neurocirujano'],
  'Dolor lumbar inespecífico': ['Fisioterapeuta', 'Traumatólogo'],
  'Cáncer de la vulva': ['Ginecólogo oncológico'],
  'Embarazo múltiple': ['Ginecólogo'],
  'Síndrome de sueño y vigilia irregulares': ['Psiquiatra', 'Neurólogo'],
  'Alcohol en el embarazo': ['Ginecólogo', 'Pediatra'],
  'Conducta nasolagrimal obstruido': ['Oftalmólogo'],
  'Pigmentación severa dental': ['Dentista - Odontólogo'],
  'Deslizamiento de la epífisis capital femoral': ['Ortopedista'],
  'Cálculos vesicales': ['Urólogo'],
  'Acné quístico': ['Dermatólogo'],
  'Esguince cervical': ['Traumatólogo', 'Fisioterapeuta'],
  'Infección de la piel por bacterias': ['Dermatólogo', 'Infectólogo'],
  'Hipertensión arterial sistémica': ['Internista', 'Cardiólogo'],
  'Embarazo molar': ['Ginecólogo'],
  'Arco alto': ['Ortopedista', 'Podólogo'],
  'Pérdida gestacional recurrente': ['Ginecólogo'],
  'Síndrome de dolor pélvico crónico': ['Ginecólogo', 'Urólogo'],
  'Enfermedad del sueño': ['Infectólogo', 'Neurólogo'],
  'Terror nocturno': ['Psiquiatra infantil', 'Psicólogo'],
  'Trastornos neurocognitivos': ['Neurólogo', 'Psiquiatra', 'Geriatra'],
  'Tetralogía de Fallot': ['Cardiólogo pediátrico'],
  'Infecciones de la glándula salival': ['Otorrinolaringólogo'],
  'Gangrena': ['Cirujano vascular', 'Angiólogo'],
  'Gangrena de tejidos blandos': ['Infectólogo', 'Cirujano general'],
  'Adenocarcinoma del estómago': ['Cirujano oncólogo', 'Gastroenterólogo'],
  'Cirrosis biliar primaria': ['Gastroenterólogo'],
  'Uña del pie encarnada': ['Podólogo', 'Dermatólogo'],
  'Pólipos cervicales': ['Ginecólogo'],
  'Demencia senil': ['Geriatra', 'Neurólogo'],
  'Cáncer de vagina': ['Ginecólogo oncológico'],
  'Acidosis metabólica': ['Internista', 'Nefrólogo'],
  'Apnea en recién nacidos': ['Neonatólogo', 'Pediatra'],
  'Vaginitis': ['Ginecólogo'],
  'Tuberculosis': ['Infectólogo', 'Neumólogo'],
  'Herpes genital': ['Infectólogo', 'Ginecólogo', 'Urólogo'],
  'Hipertensión arterial pulmonar': ['Neumólogo', 'Cardiólogo'],
  'Endotropía': ['Oftalmólogo'],
  'Gota crónica': ['Reumatólogo'],
  'Prolapso de disco intervertebral': ['Traumatólogo', 'Neurocirujano'],
  'Acidosis tubular distal renal': ['Nefrólogo'],
  'Hemorragia subaracnoidea': ['Neurocirujano'],
  'Eritema tóxico del neonato': ['Pediatra', 'Dermatólogo'],
  'Submordida': ['Ortodoncista'],
  'Tendinitis bicipital': ['Traumatólogo', 'Fisioterapeuta'],
  'Glaucoma de ángulo cerrado': ['Oftalmólogo'],
  'Reacción anafiláctica': ['Alergólogo', 'Urgenciólogo'],
  'Amebiasis hepática': ['Infectólogo', 'Gastroenterólogo'],
  'Hipotensión': ['Cardiólogo', 'Internista'],
  'Cardiomiopatía hipertrófica (CMH)': ['Cardiólogo'],
  'Pseudoartrosis': ['Traumatólogo', 'Ortopedista'],
  'Espolón calcáneo y fascitis plantar': ['Ortopedista', 'Fisioterapeuta', 'Podólogo'],
  'Síndrome de Edwards': ['Genetista'],
  'Hiperplasia endometrial benigna': ['Ginecólogo'],
  'Trastorno de la personalidad evasiva': ['Psicólogo', 'Psiquiatra'],
  'Entropión': ['Oftalmólogo'],
  'Visión corta': ['Optometrista', 'Oftalmólogo'],
  'Trastorno de la personalidad pasivo-agresiva': ['Psicólogo', 'Psiquiatra'],
  'Enterocolitis necrosante': ['Cirujano pediátrico', 'Neonatólogo'],
  'Angiodisplasia del colon': ['Gastroenterólogo'],
  'Carcinoma hepatocelular': ['Oncólogo médico', 'Gastroenterólogo'],
  'Fractura de la base del metatarso': ['Traumatólogo'],
  'Vértigo Central': ['Neurólogo', 'Otorrinolaringólogo'],
  'Absceso hepático bacteriano': ['Infectólogo', 'Gastroenterólogo'],
  'Agua en el pulmón': ['Neumólogo', 'Internista'],
  'Shock séptico': ['Especialista en Medicina Crítica y Terapia Intensiva'],
  'Colestasis': ['Gastroenterólogo'],
  'Andropausia': ['Urólogo', 'Endocrinólogo'],
  'Artritis reactiva': ['Reumatólogo'],
  'Infección sinusal': ['Otorrinolaringólogo'],
  'Conjuntivitis aguda': ['Oftalmólogo'],
  'Pinguécula': ['Oftalmólogo'],
  'Angina de Ludwig': ['Cirujano maxilofacial', 'Otorrinolaringólogo'],
  'Hiperacusia': ['Audiólogo', 'Otorrinolaringólogo'],
  'Síndrome de bradicardia-taquicardia': ['Cardiólogo'],
  'Hernia discales': ['Traumatólogo', 'Neurocirujano'],
  'Síndrome de Ehlers-Danlos': ['Genetista', 'Reumatólogo'],
  'Codependencia emocional y heridas de infancia': ['Psicólogo'],
  'HIV/SIDA': ['Infectólogo'],
  'Enfermedad pulmonar intersticial difusa': ['Neumólogo']
};

