
export const POPULAR_CITIES = [
  'Aguascalientes',
  'Chihuahua',
  'Ciudad Juárez',
  'Ciudad de México',
  'Cuernavaca',
  'Ecatepec de Morelos',
  'Guadalajara',
  'Gustavo A. Madero',
  'Iztapalapa',
  'León',
  'Mexicali',
  'Monterrey',
  'Mérida',
  'Puebla',
  'San Luis Potosí',
  'Tijuana',
  'Toluca',
  'Zapopan'
];

export const ALL_CITIES = [
  'Acapulco', 'Aguascalientes', 'Apizaco', 'Apodaca', 'Baja California', 'Baja California Sur', 
  'Benito Juárez', 'Buenavista', 'Cabo San Lucas', 'Cadereyta Jiménez', 'Campeche', 'Cancún', 
  'Chalco', 'Chiapas', 'Chicoloapan', 'Chihuahua', 'Chilpancingo', 'Chimalhuacán', 'Ciudad Acuña', 
  'Ciudad Apodaca', 'Ciudad Benito Juárez', 'Ciudad de México', 'Ciudad del Carmen', 'Ciudad Juárez', 
  'Ciudad López Mateos', 'Ciudad Madero', 'Ciudad Nicolás Romero', 'Ciudad Obregón', 'Ciudad Victoria', 
  'Coahuila', 'Coatzacoalcos', 'Colima', 'Coyoacán', 'Cuautitlán Izcalli', 'Cuautla', 'Cuauhtémoc', 
  'Cuernavaca', 'Culiacán', 'Durango', 'Ecatepec de Morelos', 'Ensenada', 'Estado de México', 'Fresnillo', 
  'García', 'General Escobedo', 'Gómez Palacio', 'Guadalajara', 'Guadalupe', 'Guanajuato', 'Guaymas', 
  'Guerrero', 'Gustavo A. Madero', 'Hermosillo', 'Hidalgo', 'Huixquilucan', 'Irapuato', 'Ixtacalco', 
  'Ixtapaluca', 'Iztapalapa', 'Jalisco', 'Jiutepec', 'Juriquilla', 'La Paz', 'La Piedad', 'León', 
  'Linares', 'Magdalena Contreras', 'Manzanillo', 'Matamoros', 'Mazatlán', 'Metepec', 'Mérida', 
  'Mexicali', 'Michoacán', 'Minatitlán', 'Miramar', 'Monclova', 'Monterrey', 'Morelia', 'Morelos', 
  'Naucalpan', 'Nayarit', 'Nezahualcóyotl', 'Nogales', 'Nuevo Casas Grandes', 'Nuevo Laredo', 
  'Nuevo León', 'Oaxaca', 'Ojo de Agua', 'Pachuca', 'Poza Rica', 'Puebla', 'Puerto Vallarta', 
  'Querétaro', 'Quintana Roo', 'Reynosa', 'Salamanca', 'Saltillo', 'San Cristóbal', 'San Francisco Coacalco', 
  'San Juan del Río', 'San Luis Potosí', 'San Luis Río Colorado', 'San Nicolás', 'San Pablo de las Salinas', 
  'San Pedro Garza Garcia', 'Santa Catarina', 'Sinaloa', 'Soledad', 'Sonora', 'Tabasco', 'Tamaulipas', 
  'Tapachula', 'Tehuacán', 'Tepic', 'Tijuana', 'Tlalnepantla', 'Tlalpan', 'Tlaquepaque', 'Toluca', 
  'Tonalá', 'Torreón', 'Tuxtla Gutiérrez', 'Uruapan', 'Veracruz', 'Villahermosa', 'Xalapa', 'Yucatán', 
  'Zacatecas', 'Zamora', 'Zapopan', 'Zapotlanejo'
].sort();

export const COMMON_SPECIALTIES = [
  "Acupuntor", "Alergólogo", "Algólogo", "Anatomopatólogo", "Anestesiólogo", "Angiólogo", 
  "Audiólogo", "Cardiólogo", "Cardiólogo pediátrico", "Cirujano bariatra", "Cirujano cardiovascular", 
  "Cirujano cardiovascular y torácico", "Cirujano de la mano", "Cirujano estético y cosmético", 
  "Cirujano general", "Cirujano maxilofacial", "Cirujano oncólogo", "Cirujano pediátrico", 
  "Cirujano plástico", "Cirujano torácico", "Cirujano vascular", "Dentista-Odontólogo", 
  "Dermatólogo", "Dermatólogo pediátrico", "Diabetólogo", "Endocrinólogo", "Endocrinólogo pediátrico", 
  "Endoscopista", "Enfermero", "Especialidad en Medicina del Enfermo Pediátrico en Estado Crítico", 
  "Especialista en Medicina Crítica y Terapia Intensiva", "Especialista en Medicina del Deporte", 
  "Especialista en Medicina del Trabajo", "Especialista en Medicina Integrada", 
  "Especialista en Obesidad y Delgadez", "Especialista en Rehabilitación y Medicina Física", 
  "Especialista en Retina Médica y Quirúrgica", "Fisioterapeuta", "Foniatra", "Gastroenterólogo", 
  "Gastroenterólogo pediátrico", "Genetista", "Geriatra", "Gerontólogo", "Ginecólogo", 
  "Ginecólogo oncológico", "Hematólogo", "Hematólogo pediatra", "Homeópata", "Infectólogo", 
  "Infectólogo pediatra", "Inmunólogo", "Internista", "Logopeda", "Médico de familia", 
  "Médico estético", "Médico general", "Naturista", "Neonatólogo", "Nefrólogo", "Nefrólogo pediatra", 
  "Neumólogo", "Neumólogo pediatra", "Neurocirujano", "Neurofisiólogo", "Neurólogo", 
  "Neurólogo pediatra", "Nutricionista", "Nutriólogo", "Nutriólogo clínico", "Odontólogo pediatra", 
  "Oftalmólogo", "Oftalmólogo pediátrico", "Oncólogo médico", "Oncólogo pediátrico", "Optometrista", 
  "Ortodoncista", "Ortopedista", "Ortopedista infantil", "Otorrinolaringólogo", 
  "Otorrinolaringólogo Pediátrico", "Patólogo Bucal", "Patólogo clínico", "Pediatra", "Podiatra", 
  "Podólogo", "Proctólogo", "Psicoanalista", "Psicólogo", "Psicopedagogo", "Psiquiatra", 
  "Psiquiatra infantil", "Quiropráctico", "Radio Oncólogo", "Radiólogo", "Radioterapeuta", 
  "Reumatólogo", "Reumatólogo pediátrico", "Sexólogo", "Técnico en diagnóstico e imagen", 
  "Terapeuta complementario", "Terapeuta ocupacional", "Traumatólogo", "Urgenciólogo", 
  "Urólogo", "Urólogo pediátrico"
].sort();

export const POPULAR_SPECIALTIES = [
  "Dentista-Odontólogo",
  "Psicólogo",
  "Pediatra",
  "Médico general",
  "Ginecólogo",
  "Internista",
  "Cirujano general",
  "Radiólogo",
  "Ortopedista",
  "Traumatólogo",
  "Oftalmólogo",
  "Psiquiatra",
  "Cardiólogo",
  "Nutricionista",
  "Otorrinolaringólogo",
  "Nutriólogo clínico",
  "Dermatólogo",
  "Fisioterapeuta",
  "Urólogo",
  "Cirujano plástico",
  "Gastroenterólogo",
  "Terapeuta complementario",
  "Anestesiólogo",
  "Especialista en Obesidad y Delgadez",
  "Endoscopista",
  "Neurocirujano",
  "Endocrinólogo",
  "Especialista en Rehabilitación y Medicina Física",
  "Nefrólogo",
  "Neonatólogo",
  "Psicoanalista",
  "Cirujano pediátrico",
  "Alergólogo"
];

export const ALL_DISEASES = [
  "Abdomen agudo", "Absceso anal", "Absceso dental", "Abuso sexual", "Abuso sexual infantil", 
  "Acalasia", "Accidente cerebrovascular isquémico", "Acné", "Acné vulgar", "Adenomiosis", 
  "Adenoides agrandadas", "Adicciones", "Aflicción", "Alergia a las proteínas de la leche (niño pequeño)", 
  "Alergia alimentaria", "Alergias", "Alergias a fármacos", "Alergias nasales", "Alopecia androgénica", 
  "Alopecia areata", "Alta miopía", "Alveolitis", "Amelogénesis imperfecta", "Amenaza de aborto", 
  "Amenorrea primaria", "Amenorrea secundaria", "Amigdalitis", "Anemia", "Aneurisma cerebral", 
  "Angina", "Angustia", "Anomalía dentaria", "Anorexia", "Anorexia nerviosa", "Ansiedad", 
  "Apatía sexual", "Apendicitis", "Apnea del sueño", "Apnea del sueño de tipo obstructivo", 
  "Arritmias", "Artritis", "Artritis reumatoide", "Asma", "Asma bronquial", "Asma pediátrico", 
  "Astigmatismo", "Ataques de pánico", "Atrición dental", "Ausencia dentaria", "Autismo", 
  "Avulsión dental", "Baja autoestima", "Bebé prematuro", "Blefaritis", "Bocio", "Bradicardia", 
  "Bronquiolitis", "Bronquitis crónica", "Bruxismo", "Bulimia nerviosa", "Bulímia", 
  "Bullying (acoso escolar)", "Bursitis", "Bursitis epitroclear", "Cambios precancerosos del cuello uterino", 
  "Cardiomiopatía isquémica", "Cardiopatía congénita", "Cardiopatía hipertensiva", "Caries", 
  "Cataratas", "Cefalea tensional", "Celulitis", "Cerumen (cera del oído)", "Cicatriz hipertrófica", 
  "Cicatriz queloide", "Cicatrices de acné", "Cirrosis", "Cistitis", "Cistitis aguda", 
  "Ciática", "Codependencia", "Codo de tenista", "Colecistitis aguda", "Colecistitis crónica", 
  "Coledocolitiasis", "Colelitiasis", "Colitis", "Colon irritable", "Comportamiento psicótico", 
  "Comportamiento suicida", "Compresión de la médula espinal", "Condiloma acuminado", "Conjuntivitis", 
  "Conjuntivitis alérgica", "Contractura cervical", "Contracturas musculares", "Control de emociones", 
  "Coronavirus COVID-19", "Criptorquidia", "Cuello torcido", "Curvatura de la columna", 
  "Cálculos biliares", "Cálculos en las vías urinarias", "Cálculos renales", "Cáncer colorrectal", 
  "Cáncer de cabeza y cuello", "Cáncer de endometrio", "Cáncer de mama", "Cáncer de piel", 
  "Cáncer de piel en célula basal", "Cáncer de próstata", "Cáncer de pulmón", "Cáncer de testículos", 
  "Cáncer de tiroides", "Cáncer del colon", "Cáncer del cuello uterino", "Cáncer del estómago", 
  "Cáncer renal", "Cáncer testicular", "Cáncer vesical", "Cólico infantil", "Degeneración macular relacionada con la edad (AMD)", 
  "Delgadez", "Demencia", "Depresión", "Depresión crónica", "Depresión en adolescentes", 
  "Depresión en los ancianos", "Depresión grave", "Depresión mayor", "Depresión neurótica (distimia)", 
  "Depresión posparto", "Dermatitis alérgica", "Dermatitis atópica", "Dermatitis del pañal", 
  "Dermatitis seborreica", "Dermatomiositis", "Derrame cerebral", "Derrame pleural", "Desgaste de cadera", 
  "Desgaste de rodilla", "Desgaste dental", "Deshidratación", "Desnutrición", "Desorden de ansiedad por separación", 
  "Deseo sexual inhibido", "Desprendimiento de retina", "Diabetes", "Diabetes gestacional", 
  "Diabetes tipo 1", "Diabetes tipo 2", "Diarrea", "Diente impactado", "Diente retenido", 
  "Dientes apiñados", "Dientes desalineados", "Discot roto", "Disfunción eréctil", "Dislalia", 
  "Dislipidemia", "Dislexia", "Disoclusión de los dientes", "Displasia cervical", "Distimia", 
  "Diverticulitis", "Dolor abdominal", "Dolor de cabeza por contracción muscular", "Dolor de espalda", 
  "Dolor de espalda inespecífico", "Dolor de muelas", "Dolor en la espalda", "Dolor en la inserción del talón", 
  "Dolor muscular", "Dolor oncológico", "Dolor post endodoncia", "Drogadicción", "Duelo", 
  "EIP (infección genital femenina)", "EPOC", "Embarazo", "Embarazo de alto riesgo", "Embarazo ectópico", 
  "Embarazo en la adolescencia", "Endometriosis", "Enfermedad articular degenerativa", "Enfermedad benigna de las mamas", 
  "Enfermedad celíaca (esprúe)", "Enfermedad de Alzheimer", "Enfermedad de Meniere", "Enfermedad de Parkinson", 
  "Enfermedad de la vesícula biliar", "Enfermedad de los ovarios poliquísticos", "Enfermedad de transmisión sexual (ETS)", 
  "Enfermedad fibroquística de las mamas", "Enfermedad inflamatoria intestinal", "Enfermedad inflamatoria pélvica (EIP)", 
  "Enfermedad periodontal - piorrea", "Enfermedad renal", "Enfermedad renal terminal", "Enfermedades de la tiroides", 
  "Enfermedades gastrointestinales", "Enuresis", "Envejecimiento cutáneo", "Epicondilitis humeral", 
  "Epilepsia", "Erosión Dental", "Escalofríos y sudoración", "Esclerosis múltiple", "Escoliosis", 
  "Esofagitis", "Esofagitis por reflujo", "Espondilitis anquilosante", "Espondiloartropatía", 
  "Esguince", "Esterilidad", "Estreñimiento", "Estrés", "Estrés laboral", "Estrés postraumático", 
  "Estrabismo", "Eyaculación precoz", "Falla renal crónica", "Faringitis", "Faringitis bacteriana", 
  "Fascitis plantar", "Fatiga crónica", "Fibrilación auricular", "Fibromialgia", "Fibrosis pulmonar", 
  "Fiebre en niños", "Fistula dental o en encía", "Fisura anal", "Fobia específica o simple", 
  "Fobia social", "Fractura coronal", "Fracturas", "Fracturas de cadera", "Fracturas de dientes", 
  "Fracturas por compresión o aplastamiento vertebral", "Gastritis", "Gastritis por estrés", 
  "Gastroenteritis", "Gastroenteritis aguda", "Gastroenteritis bacteriana con diarrea infecciosa", 
  "Gigantomastia", "Gingivitis", "Glaucoma", "Glomerulonefritis", "Halitosis", "Hemorragia cerebral", 
  "Hemorroides", "Hepatitis", "Hernia", "Hernia de disco", "Hernia hiatal", "Hernia inguinal", 
  "Hernia umbilical", "Hidrocele", "Hidrocefalia", "Hipoacusia relacionada con la edad", "Hipotiroidismo", 
  "Hipercolesterolemia", "Hipercolesterolemia familiar", "Hiperlipidemia", "Hipermetropía", 
  "Hipertensión", "Hipertensión inducida por el embarazo", "Hipertiroidismo", "Hipertrofia (hiperplasia) prostática benigna", 
  "Hombro congelado", "Hígado graso", "Ictericia del recién nacido", "Impactación dental", 
  "Incontinencia urinaria de esfuerzo", "Infarto agudo de miocardio", "Infarto cerebral", "Infarto de miocardio", 
  "Infección aguda del oído", "Infección del oído", "Infección dental", "Infección urinaria en adultos", 
  "Infección urinaria en niños", "Infertilidad", "Insomnio", "Insomnio crónico", "Inestabilidad Glenohumeral", 
  "Insuficiencia aguda del riñón", "Insuficiencia arterial", "Insuficiencia cardíaca", "Insuficiencia crónica del riñón", 
  "Insuficiencia renal", "Insuficiencia renal aguda", "Intolerancia a la lactosa", "Intolerancia al gluten", 
  "Juanetes", "Labio leporino y paladar hendido", "Laringitis", "Lesión de Ligamentarias de Rodilla", 
  "Lesión de Manguito Rotador", "Lesión facial", "Lesiones de Menisco", "Lesiones de cartílago articular", 
  "Lesiones deportivas", "Lesiones ligamentarias en mano y muñeca", "Leucemia", "Linfoma de Hodgkin", 
  "Litiasis renal", "Lumbalgia", "Lunar", "Lupus", "Luto", "Luxación Acromioclavicular", 
  "Maltrato psicológico y abandono infantil", "Manchas de la edad", "Manchas en dientes", "Masas cutáneas de grasa", 
  "Melanoma", "Melasma", "Menopausia", "Mieloma múltiple", "Migraña", "Miomas uterinos", 
  "Miopía", "Mordida abierta", "Movilidad dentaria", "Muelas del juicio", "Nariz bulbosa", 
  "Nefropatía diabética", "Nefritis lúpica", "Neumonía", "Neurosis histérica", "Nódulo tiroideo", 
  "Nutrición inadecuada", "Obesidad", "Obesidad mórbida", "Obstrucción intestinal", "Oclusión dental defectuosa", 
  "Ojo rojo", "Osteoartritis", "Osteoartrosis", "Osteoporosis", "Otitis", "Ovarios poliquísticos", 
  "Pancreatitis", "Pancreatitis aguda", "Parálisis cerebral", "Parálisis facial", "Periodontitis", 
  "Pie Diabético", "Pie plano", "Presbicia", "Presión arterial alta (Hipertensión)", "Prognatismo", 
  "Prolapso uterino", "Preeclampsia", "Psoriasis", "Pterigión", "Pólipos nasales", "Pérdida de dientes", 
  "Quemaduras", "Queratocono", "Quistes ováricos", "Radiculopatía lumbar", "Rechazo al trasplante", 
  "Reflujo gastroesofágico", "Reflujo gastroesofágico en bebés", "Resfriado común", "Resistencia a la insulina", 
  "Retinopatía diabética", "Rinitis alérgica", "Sangrado uterino anormal", "Sangrado uterino disfuncional", 
  "Sensibilidad dentaria", "Sinusitis", "Sobremordida", "Sobrepeso", "Síndrome de burnout", 
  "Síndrome de caídas", "Síndrome de dolor miofascial", "Síndrome de los ovarios poliquísticos (PCOS)", 
  "Síndrome de pinzamiento del hombro", "Síndrome de Sjogren", "Síndrome del colon irritable (IBS)", 
  "Síndrome del ojo seco", "Síndrome metabólico", "Síndrome nefrótico", "Síntomas gastrointestinales", 
  "Tabaquismo", "Taquicardia", "Tendinitis", "Tendinitis del manguito de los rotadores", "Tendinitis, esguinces articulares", 
  "Tenosinovitis", "Trastorno bipolar", "Trastorno bipolar afectivo", "Trastorno de adaptación", 
  "Trastorno de alimentación en la lactancia y en la primera infancia", "Trastorno de ansiedad", 
  "Trastorno de ansiedad generalizada", "Trastorno de hiperactividad y déficit de atención (TDAH)", 
  "Trastorno de identidad de género", "Trastorno de la conducta alimentaria", "Trastorno del espectro autista (TEA)", 
  "Trastorno del sueño por ansiedad", "Trastorno depresivo grave", "Trastorno límite de la personalidad", 
  "Trastorno obsesivo compulsivo (TOC)", "Trastorno por atracón", "Trastornos cardiovasculares", 
  "Trastornos de la ATM", "Trastornos de la articulación temporomandibular", "Trastornos de la menstruación", 
  "Trastornos de la personalidad", "Trastornos del aprendizaje", "Trastornos del sueño", "Trastornos del sueño en personas mayores", 
  "Trauma ocular", "Traumatismo facial", "Trombosis venosa profunda", "Tuberculosis pulmonar", 
  "Tumor cerebral en adultos", "Urticaria", "Venas varicosas", "Verrugas", "Verrugas genitales", 
  "Virus del papiloma humano (VPH)", "Vitiligo", "Vértigo postural benigno", "Úlceras bucales"
].sort();
