
export const POPULAR_CITIES = [
  'Aguascalientes',
  'Chihuahua',
  'Ciudad Juárez',
  'Ciudad de México',
  'Cuernavaca',
  'Ecatepec de Morelos',
  'Guadalajara',
  'Gustavo A. Madero',
  'Iztapalapa',
  'León',
  'Mexicali',
  'Monterrey',
  'Mérida',
  'Puebla',
  'San Luis Potosí',
  'Tijuana',
  'Toluca',
  'Zapopan'
];

export const ALL_CITIES = [
  'Acapulco', 'Aguascalientes', 'Apizaco', 'Apodaca', 'Baja California', 'Baja California Sur', 
  'Benito Juárez', 'Buenavista', 'Cabo San Lucas', 'Cadereyta Jiménez', 'Campeche', 'Cancún', 
  'Chalco', 'Chiapas', 'Chicoloapan', 'Chihuahua', 'Chilpancingo', 'Chimalhuacán', 'Ciudad Acuña', 
  'Ciudad Apodaca', 'Ciudad Benito Juárez', 'Ciudad de México', 'Ciudad del Carmen', 'Ciudad Juárez', 
  'Ciudad López Mateos', 'Ciudad Madero', 'Ciudad Nicolás Romero', 'Ciudad Obregón', 'Ciudad Victoria', 
  'Coahuila', 'Coatzacoalcos', 'Colima', 'Coyoacán', 'Cuautitlán Izcalli', 'Cuautla', 'Cuauhtémoc', 
  'Cuernavaca', 'Culiacán', 'Durango', 'Ecatepec de Morelos', 'Ensenada', 'Estado de México', 'Fresnillo', 
  'García', 'General Escobedo', 'Gómez Palacio', 'Guadalajara', 'Guadalupe', 'Guanajuato', 'Guaymas', 
  'Guerrero', 'Gustavo A. Madero', 'Hermosillo', 'Hidalgo', 'Huixquilucan', 'Irapuato', 'Ixtacalco', 
  'Ixtapaluca', 'Iztapalapa', 'Jalisco', 'Jiutepec', 'Juriquilla', 'La Paz', 'La Piedad', 'León', 
  'Linares', 'Magdalena Contreras', 'Manzanillo', 'Matamoros', 'Mazatlán', 'Metepec', 'Mérida', 
  'Mexicali', 'Michoacán', 'Minatitlán', 'Miramar', 'Monclova', 'Monterrey', 'Morelia', 'Morelos', 
  'Naucalpan', 'Nayarit', 'Nezahualcóyotl', 'Nogales', 'Nuevo Casas Grandes', 'Nuevo Laredo', 
  'Nuevo León', 'Oaxaca', 'Ojo de Agua', 'Pachuca', 'Poza Rica', 'Puebla', 'Puerto Vallarta', 
  'Querétaro', 'Quintana Roo', 'Reynosa', 'Salamanca', 'Saltillo', 'San Cristóbal', 'San Francisco Coacalco', 
  'San Juan del Río', 'San Luis Potosí', 'San Luis Río Colorado', 'San Nicolás', 'San Pablo de las Salinas', 
  'San Pedro Garza Garcia', 'Santa Catarina', 'Sinaloa', 'Soledad', 'Sonora', 'Tabasco', 'Tamaulipas', 
  'Tapachula', 'Tehuacán', 'Tepic', 'Tijuana', 'Tlalnepantla', 'Tlalpan', 'Tlaquepaque', 'Toluca', 
  'Tonalá', 'Torreón', 'Tuxtla Gutiérrez', 'Uruapan', 'Veracruz', 'Villahermosa', 'Xalapa', 'Yucatán', 
  'Zacatecas', 'Zamora', 'Zapopan', 'Zapotlanejo'
].sort();

export const COMMON_SPECIALTIES = [
  "Acupuntor", "Alergólogo", "Algólogo", "Anatomopatólogo", "Anestesiólogo", "Angiólogo", 
  "Audiólogo", "Cardiólogo", "Cardiólogo pediátrico", "Cirujano bariatra", "Cirujano cardiovascular", 
  "Cirujano cardiovascular y torácico", "Cirujano de la mano", "Cirujano estético y cosmético", 
  "Cirujano general", "Cirujano maxilofacial", "Cirujano oncólogo", "Cirujano pediátrico", 
  "Cirujano plástico", "Cirujano torácico", "Cirujano vascular", "Dentista - Odontólogo", 
  "Dermatólogo", "Dermatólogo pediátrico", "Diabetólogo", "Endocrinólogo", "Endocrinólogo pediátrico", 
  "Endoscopista", "Enfermero", "Especialidad en Medicina del Enfermo Pediátrico en Estado Crítico", 
  "Especialista en Medicina Crítica y Terapia Intensiva", "Especialista en Medicina del Deporte", 
  "Especialista en Medicina del Trabajo", "Especialista en Medicina Integrada", 
  "Especialista en Obesidad y Delgadez", "Especialista en Rehabilitación y Medicina Física", 
  "Especialista en Retina Médica y Quirúrgica", "Fisioterapeuta", "Foniatra", "Gastroenterólogo", 
  "Gastroenterólogo pediátrico", "Genetista", "Geriatra", "Gerontólogo", "Ginecólogo", 
  "Ginecólogo oncológico", "Hematólogo", "Hematólogo pediatra", "Homeópata", "Infectólogo", 
  "Infectólogo pediatra", "Inmunólogo", "Internista", "Logopeda", "Médico de familia", 
  "Médico estético", "Médico general", "Naturista", "Neonatólogo", "Nefrólogo", "Nefrólogo pediatra", 
  "Neumólogo", "Neumólogo pediatra", "Neurocirujano", "Neurofisiólogo", "Neurólogo", 
  "Neurólogo pediatra", "Nutricionista", "Nutriólogo", "Nutriólogo clínico", "Odontólogo pediatra", 
  "Oftalmólogo", "Oftalmólogo pediátrico", "Oncólogo médico", "Oncólogo pediátrico", "Optometrista", 
  "Ortodoncista", "Ortopedista", "Ortopedista infantil", "Otorrinolaringólogo", 
  "Otorrinolaringólogo Pediátrico", "Patólogo Bucal", "Patólogo clínico", "Pediatra", "Podiatra", 
  "Podólogo", "Proctólogo", "Psicoanalista", "Psicólogo", "Psicopedagogo", "Psiquiatra", 
  "Psiquiatra infantil", "Quiropráctico", "Radio Oncólogo", "Radiólogo", "Radioterapeuta", 
  "Reumatólogo", "Reumatólogo pediátrico", "Sexólogo", "Técnico en diagnóstico e imagen", 
  "Terapeuta complementario", "Terapeuta ocupacional", "Traumatólogo", "Urgenciólogo", 
  "Urólogo", "Urólogo pediátrico"
].sort();

export const POPULAR_SPECIALTIES = [
  "Dentista - Odontólogo",
  "Psicólogo",
  "Pediatra",
  "Médico general",
  "Ginecólogo",
  "Internista",
  "Cirujano general",
  "Radiólogo",
  "Ortopedista",
  "Traumatólogo",
  "Oftalmólogo",
  "Psiquiatra",
  "Cardiólogo",
  "Nutricionista",
  "Otorrinolaringólogo",
  "Nutriólogo clínico",
  "Dermatólogo",
  "Fisioterapeuta",
  "Urólogo",
  "Cirujano plástico",
  "Gastroenterólogo",
  "Anestesiólogo",
  "Endoscopista",
  "Neurocirujano",
  "Endocrinólogo",
  "Nefrólogo",
  "Neonatólogo",
  "Psicoanalista",
  "Cirujano pediátrico",
  "Alergólogo"
];

export const ALL_DISEASES = [
  "Ansiedad", "Depresión", "Duelo", "Estrés", "Codependencia", "Hipertensión",
  "Caries", "Estrés postraumático", "Trastorno de conducta", "Diabetes", "Dislipidemia", "Depresión en adolescentes",
  "Bruxismo", "Síndrome metabólico", "Dolor de muelas", "Obesidad", "Trastorno obsesivo compulsivo (TOC)", "Infección dental",
  "Sobrepeso", "Fracturas de dientes", "Desgaste dental", "Ataques de pánico", "Bullying (acoso escolar)", "Pérdida de dientes",
  "Dientes desalineados", "Dientes apiñados", "Estrés laboral", "Angustia", "Enfermedad periodontal - piorrea", "Lesiones deportivas",
  "Trastorno de ansiedad", "Trastorno de ansiedad generalizada", "Gastritis", "Colon irritable", "Virus del papiloma humano (VPH)", "Diabetes gestacional",
  "Miomas uterinos", "Embarazo", "Trastornos de la personalidad", "Menopausia", "Ciática", "Trastorno de hiperactividad y déficit de atención (TDAH)",
  "Depresión crónica", "Conducta agresiva", "Embarazo de alto riesgo", "Desnutrición", "Endometriosis", "Insuficiencia cardíaca",
  "Amenaza de aborto", "Adicciones", "Apendicitis", "Comportamiento suicida", "Síndrome de pinzamiento del hombro", "Faringitis",
  "Diabetes tipo 2", "Sangrado uterino disfuncional", "Asma", "Gingivitis", "Maltrato psicológico y abandono infantil", "Abdomen agudo",
  "Desorden de ansiedad por separación", "Hernia de disco", "Tendinitis del manguito de los rotadores", "Fobia específica o simple", "Hernia inguinal", "Neumonía",
  "Colecistitis aguda", "Cataratas", "Reflujo gastroesofágico", "Diverticulitis", "Enfermedad articular degenerativa", "Tendinitis",
  "Radiculopatía lumbar", "Depresión neurótica (distimia)", "Infertilidad", "Rinitis alérgica", "Cálculos biliares", "Periodontitis",
  "Manchas en dientes", "Absceso dental", "Dolor abdominal", "Miopía", "Osteoporosis", "Diente retenido",
  "Lesión de Ligamentarias de Rodilla", "Contractura cervical", "Lesiones de cartílago articular", "Anorexia nerviosa", "Asma pediátrico", "Trastornos de la articulación temporomandibular",
  "Lesiones de Menisco", "Luto", "Dermatitis atópica", "Astigmatismo", "Depresión grave", "Colecistitis crónica",
  "Hernia hiatal", "Faringitis bacteriana", "Sensibilidad dentaria", "Hernia", "Bulimia nerviosa", "Hernia umbilical",
  "Reflujo gastroesofágico en bebés", "Dermatitis del pañal", "Cólico infantil", "Alveolitis", "Colitis", "Dolor muscular",
  "Cáncer de piel", "Retinopatía diabética", "Movilidad dentaria", "Demencia", "Bronquiolitis", "Conjuntivitis",
  "Nutrición inadecuada", "Mordida abierta", "Diarrea", "Cáncer de próstata", "Anemia", "Cardiomiopatía isquémica",
  "Trastornos del aprendizaje", "Halitosis", "Glaucoma", "Síndrome del ojo seco", "Fascitis plantar", "Amigdalitis",
  "Fiebre en niños", "Alergia alimentaria", "Diente impactado", "Migraña", "Hipermetropía", "Hiperlipidemia",
  "Sinusitis", "Infección urinaria en niños", "Oclusión dental defectuosa", "Lesión de Manguito Rotador", "Acné", "Pterigión",
  "Arritmias", "Pie plano", "Baja autoestima", "Hipertiroidismo", "Sobremordida", "Hipercolesterolemia",
  "Esquizofrenia", "Atrición dental", "Trastorno bipolar", "Alergias", "Vértigo postural benigno", "Fracturas",
  "Lumbalgia", "Dolor de cabeza por contracción muscular", "Cefalea tensional", "Infarto agudo de miocardio", "Impactación dental", "Angina",
  "Prognatismo", "Cáncer renal", "Gastroenteritis", "Síntomas gastrointestinales", "Disfunción eréctil", "Cáncer del colon",
  "Úlceras bucales", "Gastritis por estrés", "Trastornos de la ATM", "Curvatura de la columna", "Alergias nasales", "Otitis",
  "Alopecia androgénica", "Epilepsia", "Alopecia areata", "Incontinencia urinaria de esfuerzo", "Enfermedad de transmisión sexual (ETS)", "Bebé prematuro",
  "Verrugas", "Infarto de miocardio", "Bronquitis crónica", "Desprendimiento de retina", "Eyaculación precoz", "Pólipos nasales",
  "Cáncer de pulmón", "Enfermedad de Parkinson", "Fibrilación auricular", "Ausencia dentaria", "Bursitis", "Laringitis",
  "Luxación Acromioclavicular", "Cáncer del cuello uterino", "Cálculos en las vías urinarias", "Enfermedad de Alzheimer", "Cáncer de mama", "Quistes ováricos",
  "Bradicardia", "Neurosis histérica", "Hígado graso", "Melasma", "Depresión mayor", "Disoclusión de los dientes",
  "Gastroenteritis aguda", "Cáncer de tiroides", "Varicocele", "Estreñimiento", "Cáncer testicular", "Cardiopatía hipertensiva",
  "Enfermedad benigna de las mamas", "Cicatriz hipertrófica", "Síndrome de los ovarios poliquísticos (PCOS)", "Contracturas musculares", "Trastornos del sueño", "Nefropatía diabética",
  "Cáncer de los ovarios", "Cicatriz queloide", "Pancreatitis", "Apnea del sueño de tipo obstructivo", "Cáncer vesical", "Cambios precancerosos del cuello uterino",
  "Trastornos de la menstruación", "Hipertrofia (hiperplasia) prostática benigna", "Fobia social", "Trastorno de la conducta alimentaria", "Cirrosis", "Psoriasis",
  "Hemorroides", "Ovarios poliquísticos", "Obesidad mórbida", "Depresión posparto", "Vitiligo", "Síndrome de burnout",
  "Pie Diabético", "Osteoartrosis", "Manchas de la edad", "Distimia", "Conjuntivitis alérgica", "Fracturas por compresión o aplastamiento vertebral",
  "Hipotiroidismo", "Desgaste de cadera", "Resfriado común", "Artritis reumatoide", "Hepatitis", "Codo de tenista",
  "Diabetes tipo 1", "Depresión en los ancianos", "Preeclampsia", "Sangrado uterino anormal", "Trastorno de adaptación", "Urticaria",
  "Dolor en la inserción del talón", "Cálculos renales", "Embarazo ectópico", "Dermatitis alérgica", "Cáncer colorrectal", "Asma bronquial",
  "Enfermedad de la vesícula biliar", "Lesión facial", "Heridas", "Esofagitis por reflujo", "EIP (infección genital femenina)", "Coronavirus COVID-19",
  "Coledocolitiasis", "Tumor cerebral en adultos", "Anorexia", "Tendinitis, esguinces articulares", "Fibromialgia", "Lunar",
  "Queratocono", "Hemorragia cerebral", "Embarazo en la adolescencia", "Enfermedad de los ovarios poliquísticos", "Delgadez", "Colelitiasis",
  "Fracturas de cadera", "Deseo sexual inhibido", "Abuso sexual", "Osteoartritis", "Glomerulonefritis", "Infección urinaria en adultos",
  "Fisura anal", "Muelas del juicio", "Intolerancia a la lactosa", "Trastorno de alimentación en la lactancia y en la primera infancia", "Aneurisma cerebral", "Síndrome del colon irritable (IBS)",
  "Tabaquismo", "Gigantomastia", "Prolapso uterino", "Bocio", "Celulitis", "Parálisis facial",
  "Bulímia", "Derrame pleural", "Hipertensión inducida por el embarazo", "Hipoacusia relacionada con la edad", "Fatiga crónica", "Aflicción",
  "Anomalía dentaria", "Trastorno por atracón", "Trastornos cardiovasculares", "Hidrocefalia", "Displasia cervical", "Epicondilitis humeral",
  "Apnea del sueño", "Dermatitis seborreica", "Enfermedades de la tiroides", "Artrosis", "Esguince", "Dolor de espalda inespecífico",
  "Verrugas genitales", "Alergia a las proteínas de la leche (niño pequeño)", "Gastroenteritis bacteriana con diarrea infecciosa", "Cicatrices de acné", "Lupus", "Artritis",
  "Enfermedad inflamatoria pélvica (EIP)", "Degeneración macular relacionada con la edad (AMD)", "Trastorno del espectro autista (TEA)", "Cáncer del estómago", "Falla renal crónica", "Esterilidad",
  "Condiloma acuminado", "Resistencia a la insulina", "Estrabismo", "Trastorno bipolar afectivo", "Apatía sexual", "Acné vulgar",
  "Trastornos del sueño en personas mayores", "Desgaste de rodilla", "Labio leporino y paladar hendido", "Traumatismo facial", "EPOC", "Cistitis aguda",
  "Dislexia", "Enfermedad fibroquística de las mamas", "Enfermedades gastrointestinales", "Envejecimiento cutáneo", "Escoliosis", "Ictericia del recién nacido",
  "Compresión de la médula espinal", "Disco roto", "Deshidratación", "Blefaritis", "Dolor post endodoncia", "Dolor oncológico",
  "Cáncer de testículos", "Masas cutáneas de grasa", "Presión arterial alta (Hipertensión)", "Enuresis", "Amelogénesis imperfecta", "Criptorquidia",
  "Cardiopatía congénita", "Hidrocele", "Autismo", "Trombosis venosa profunda", "Dolor en la espalda", "Hombro congelado",
  "Avulsión dental", "Parálisis cerebral", "Fractura coronal", "Obstrucción intestinal", "Espondilitis anquilosante", "Insuficiencia arterial",
  "Nódulo tiroideo", "Trastorno depresivo grave", "Esclerosis múltiple", "Síndrome nefrótico", "Enfermedad renal", "Abuso sexual infantil",
  "Quemaduras", "Adenoides agrandadas", "Cáncer de piel en célula basal", "Cistitis", "Síndrome de dolor miofascial", "Síndrome de caídas",
  "Lesiones ligamentarias en mano y muñeca", "Nefritis lúpica", "Rechazo al trasplante", "Trastorno límite de la personalidad", "Alergias a fármacos", "Tuberculosis pulmonar",
  "Fibrosis pulmonar", "Síndrome de Sjogren", "Ojo rojo", "Comportamiento psicótico", "Amenorrea primaria", "Venas varicosas",
  "Linfoma de Hodgkin", "Dermatomiositis", "Enfermedad de Meniere", "Acalasia", "Alta miopía", "Infección aguda del oído",
  "Esofagitis", "Trastorno de identidad de género", "Cuello torcido", "Trauma ocular", "Melanoma", "Erosión Dental",
  "Derrame cerebral", "Adenomiosis", "Trastorno del sueño por ansiedad", "Absceso anal", "Enfermedad celíaca (esprúe)", "Insuficiencia renal aguda",
  "Cerumen (cera del oído)", "Cáncer de cabeza y cuello", "Intolerancia al gluten", "Juanetes", "Infección del oído", "Presbicia",
  "Fistula dental o en encía", "Hipercolesterolemia familiar", "Espondiloartropatía", "Insuficiencia renal", "Insuficiencia aguda del riñón", "Enfermedad renal terminal",
  "Tenosinovitis", "Enfermedad inflamatoria intestinal", "Dislalia", "Bursitis epitroclear", "Amenorrea secundaria", "Infarto cerebral",
  "Cáncer de endometrio", "Insuficiencia crónica del riñón", "Mieloma múltiple", "Nariz bulbosa", "Control de emociones", "Pancreatitis aguda",
  "Accidente cerebrovascular isquémico", "Inestabilidad Glenohumeral", "Litiasis renal", "Insomnio crónico", "Taquicardia", "Leucemia",
  "Drogadicción", "Acidez", "Contractura de Dupuytren", "Insuficiencia venosa crónica", "Hipoacusia en bebés", "Trastornos en la alimentación del anciano",
  "Lesión cerebral en bebés", "Artritis psoriásica", "Linfoma no Hodgkin", "Ausencia de la menstruación", "Infección aguda de las vías urinarias (IVU aguda)", "Orzuelo",
  "Dentición", "Hipertensión pulmonar", "Trastornos de la voz", "Parálisis espástica", "Pinzamiento Subacromial", "Trastornos por inmunodeficiencia",
  "Niveles elevados de colesterol y triglicéridos", "Estenosis aórtica", "Hipotiroidismo en adultos", "Síndrome de dificultad respiratoria en neonatos", "Síndrome del túnel carpiano", "Atrofia muscular espinal",
  "Trastornos asociados con el vértigo", "Bronconeumonía", "Tumor cerebral en niños", "Degeneración macular", "Agujero macular", "Aneurisma",
  "Asimetría facial", "Herpes zóster (culebrilla)", "Abuso del alcohol", "Esclerodermia", "Falta de fluidez en el lenguaje", "Insomnio psicofisiológico (aprendido)",
  "Fluorosis", "Miastenia grave", "Coágulo en las piernas", "Adherencias", "Coagulopatía", "Psicosis",
  "Estenosis pilórica", "Dolor de rodilla", "Púrpura trombocitopénica idiopática (ITP)", "Postura jorobada", "Tapón de cerumen", "Violencia de género",
  "Varicela", "Queratoglobo", "Accidente cerebrovascular", "Úlcera gastroduodenal aguda", "Rodilla vara", "Dependencia del alcohol",
  "Gota aguda", "Absceso del ano y el recto", "Enfermedades y dolor crónico", "Rosácea", "Pie equino varo", "Enfermedades renales",
  "Trastornos de lenguaje", "Agrandamiento de la próstata", "Síndrome de Down", "Convulsiones febriles", "Divertículo de Meckel", "Traumatismo dental",
  "Cáncer", "Dolor de cabeza", "Úlceras e infecciones corneales", "Cervicitis", "Flebitis", "Crisis respiratoria en recién nacidos",
  "Fimosis", "Bursitis retrocalcánea", "Osteoporosis por Climaterio", "Tristeza", "Ronquido", "Dependencia emocional",
  "Trastornos de las glándulas salivales", "Fibroadenoma de mama", "Reducción de grasa (adiposidades)", "Anemia ferropénica en niños", "Cardiopatías", "Dermatitis por contacto",
  "Demencia vascular", "Deseo sexual hipoactivo", "Aversión al sexo", "Insuficiencia venosa", "Pérdida auditiva relacionada con la edad", "Cardiomiopatía dilatada",
  "Tumores o protuberancias en las mamas", "Dedos en garra", "Anemia por deficiencia de hierro en los niños", "Estreñimiento en niños", "Influenza", "Cifoescoliosis",
  "Estenosis mitral", "Enfermedad cerebrovascular", "Trombocitopenia", "Alopecia en hombres", "Absceso de Bartolino", "Trastorno de oposición desafiante",
  "Uveítis", "Edema macular", "Atresia esofágica", "Peritonitis", "Angina inestable", "Colitis ulcerosa",
  "Tumor nasal", "Abuso de drogas y farmacodependencia", "Dolor de nervio o dolor nervioso", "Trastornos hormonales", "Retraso del desarrollo", "Amenaza de aborto espontáneo",
  "Malabsorción", "Trastorno del desarrollo de la lectura", "Discapacidad intelectual", "Enfermedad vascular periférica", "Incontinencia fecal", "Parálisis del nervio facial",
  "Celiaquía", "Fractura de la pelvis", "Ambliopía", "Síndrome de dolor regional complejo", "Hemofilia", "Síndrome del intestino corto",
  "Infección crónica de los senos paranasales", "Síncope", "Fractura de antebrazo", "Obesidad infantil", "Aborto incompleto", "Agrandamiento de adenoides",
  "Hidrocele de la túnica vaginal del testículo (proceso vaginal)", "Gingivitis ulceronecrosante aguda", "Estenosis de la válvula aórtica", "Dolor somático", "Adherencia intraperitoneal", "Candidiasis vaginal",
  "Infección de las vías urinarias (IVU) en adultos", "El tartamudeo y los niños", "Cálculos en el tracto urinario", "Ano imperforado", "Neuronitis vestibular", "Falla cardíaca",
  "Dedo del pie en martillo", "Hipocondría", "Desregulación disruptiva del estado de ánimo", "Trastorno de pánico con agorafobia", "Obstrucción del conducto lagrimal", "Capsulitis adhesiva",
  "Sordera", "Dolor terminal", "Síndrome del intestino irritable", "Hiperhidrosis", "Displasia del desarrollo de la cadera", "Lesión corneal",
  "Absceso periamigdalino", "Gastrosquisis", "Cáncer del páncreas", "Mucocele", "Cervicalgía", "Vulvovaginitis",
  "Colesterol", "Ascitis", "Neuropatía diabética", "Cáncer bucal", "Onicomicosis", "Perimenopausia",
  "Distrofia muscular", "Parto prematuro", "Alcoholismo", "Ateroesclerosis", "Miocardiopatías", "Prolapso rectal",
  "Adenoma de tiroides", "Piedras en el riñón", "Caspa", "Angina crónica", "Linfedema", "Cáncer de vejiga",
  "Cáncer de pene", "Fibrosis quística", "Crup", "Arrancamiento compulsivo del cabello", "Verrugas del pene", "Fractura de fémur",
  "Síndrome de resistencia a la insulina", "Acné rosácea", "Pubertad precoz", "Retraso en el desarrollo psicomotor", "Infección urinaria recurrente", "Accidente cerebrovascular hemorrágico",
  "Diplopía (visión doble)", "Hematoma epidural", "Miedos y fobias", "Comunicación interauricular", "Cáncer endometrial", "Delirium",
  "Balanitis", "Conducta", "Úlceras venosas", "Codo de niñera", "Aborto espontáneo", "Trastornos del desarrollo sexual",
  "Enfermedad de Osgood-Schlatter", "Hiperplasia prostática", "Oclusión de las venas retinianas", "Laberíntitis", "Hiperparatiroidismo", "Cálculo en el conducto biliar",
  "Quiste sebáceo", "Artritis gotosa aguda", "Craneosinostosis", "Mastopatia fibroquística", "Subluxación vertebral", "Restricción del crecimiento intrauterino",
  "Ludopatía", "Afecciones asociadas con la ictericia", "Úlcera péptica", "Defensas bajas", "Síndrome de apnea obstructiva del sueño", "Lesiones de Lefort",
  "Molusco contagioso", "Embarazo abdominal", "Tos crónica", "Angina estable", "Colangitis", "Infección recurrente de las vías urinarias",
  "Displasia congénita de la cadera", "Encefalopatía hepática", "Enfermedad ovárica poliquística", "TEPT", "Trauma", "Esclerosis sistémica",
  "Trastorno de personalidad narcisista", "Lesión maxilofacial", "Pericarditis", "Síndrome de dolor pélvico", "Ataque cardíaco", "Fibromiositis",
  "Cetoacidosis diabética", "Embarazo de bajo riesgo", "Cáncer de útero", "TAG", "Nefrolitiasis", "Sinusitis crónica",
  "Cáncer de piel escamocelular", "Adenomioma", "Malformación anorrectal", "Cardiopatía coronaria", "Infección del riñón", "Deficiencia de la hormona del crecimiento",
  "Infección por VIH", "Congoja", "Lesiones ligamentarias de rodillas", "Enfermedades terminales", "Enfermedad de von Willebrand", "Malformación arteriovenosa cerebral",
  "Hematoma subdural crónico", "Absceso de las amígdalas", "Trastorno de la personalidad esquizoide", "Relaciones insanas", "Trastornos de la marcha", "Nevos",
  "Enfermedad de Legg-Calve-Perthes", "Visión baja", "Cáncer del hígado", "Hipospadias", "Síndrome de distrofia simpática refleja", "Deformidad en valgo del dedo gordo",
  "Miedo", "Delirio", "Encopresis", "Inseguridad", "Alergia al moho, la caspa y el polvo", "Aneurisma aórtico",
  "Accidente cardiovascular", "Diarrea crónica", "Cambios en la piel inducidos por el sol", "Deficiencia de vitamina D", "Hombro doloroso", "Cefalea en racimo",
  "Peritonitis asociada con diálisis", "Párpados caídos", "Lesión renal aguda", "Meningioma en adultos", "Personalidad psicopática", "Neuralgia glosofaríngea",
  "Alergias a las mascotas", "Comunicación interventricular", "Úlcera gástrica", "Queratosis: tumores benignos de la piel", "Espondilitis", "Calvicie de patrón masculino",
  "Gestión de emociones", "Infección complicada de las vías urinarias", "Deficiencia articulatoria", "Trastorno fonológico", "Gingivoestomatitis", "Hepatitis C",
  "Dermatitis y úlceras por estasis", "Celotipia", "Infertilidad masculina", "Bacteriuria asintomática", "Hombro de tenista", "Displasia broncopulmonar",
  "Sonrisa gingival", "Desviación Septal", "Enfermedad de Crohn", "Cáncer laríngeo", "Hipoglucemia", "Aborto electivo o terapéutico",
  "Hiperlordosis", "Hombro de nadador", "Artritis por gota crónica", "Tumor de la médula espinal", "Trastorno de pánico", "Enfermedad de Hirschsprung",
  "Arterioesclerosis", "Dolor de hombro", "Hernia crural", "Infecciones frecuentes de garganta", "Acalasia esofágica", "Reflujo vesicoureteral",
  "Insuficiencia en el crecimiento", "Diarrea bacteriana", "Leiomioma", "Infección urinaria complicada", "Trastorno Déficit de atención e hiperactividad", "Nutrición y salud emocional",
  "Ptosis", "Tumor cerebral canceroso (metastásico)", "Acumulación de placa en las arterias", "Almorranas", "Lipoma cervical", "Asma inducido por el ejercicio",
  "Enfermedad cardíaca isquémica", "Tartamudeo", "Blefaroespasmo", "Diverticulosis", "Neoplasia intraepitelial cervical", "Ectropión",
  "Neuropatía del nervio ciático", "Daño renal", "Absceso cerebral", "Gastritis crónica", "Neumotórax", "Neuralgia del trigémino",
  "Exceso de flujo vaginal - leucorrea", "Calvicie de patrón femenino", "Temblor inducido por fármacos", "Patologías del crecimiento", "Hipotiroidismo congénito", "Adherencia pélvica",
  "Pesadillas constantes", "Cifosis", "Tumor del riñón o Tumor renal", "Atresia duodenal", "Enfermedad coronaria (CHD)", "Fístula gastrointestinal",
  "Ronchas o habones", "Cardiopatía cianótica", "Bocio multinodular tóxico", "Adenoma hipofisario secretor de prolactina", "Hiperplasia suprarrenal congénita", "Parálisis de Erb-Duchenne",
  "Síndrome de Williams", "Espasticidad", "Adenoma secretante", "Mioma", "Eclampsia", "Trastorno esquizoafectivo",
  "Estenosis raquídea", "Cataratas congénitas", "Próstata agrandada", "Infección crónica del oído", "Sangrado nasal", "Trastorno del control de los impulsos",
  "Dolor de columna", "Dolor de espalda", "Absceso mamario", "Trastorno del desarrollo del lenguaje expresivo", "Ovario poliquístico", "Condromalacia rotuliana",
  "Agorafobia", "Pielonefritis", "Subluxación", "Tromboflebitis", "Pólipos colorrectales", "Cáncer de esófago",
  "Artritis bacteriana", "Codo dislocado en niños", "Tumor medular", "Síndrome de Turner", "Poliquistosis ovárica", "Deseo sexual hiperactivo",
  "Infección viral de las vías respiratorias bajas", "Displasia del desarrollo de la articulación de la cadera", "Disfunción de la trompa de Eustaquio", "Hernia diafragmática", "Perforación gastrointestinal", "Dolor de cadera",
  "Absceso intraabdominal", "Laringotraqueobronquitis aguda", "Conducto arterial persistente", "Estenosis uretral", "Síndrome femororrotuliano", "Cáncer de garganta",
  "Trastorno de dolor", "Amebiasis", "Eccema", "Riñones poliquísticos", "Arcos caídos", "Dengue",
  "Afasia", "Eliminación de amalgamas", "Periimplantitis", "Alergia de insectos", "Gripe", "Inclusión dentaria",
  "Hidronefrosis", "Pie cavo", "Síndrome antifosfolípido", "Eyaculación retrasada en el sexo", "Espondilolistesis", "Temblor",
  "Anquiloglosia", "Proctitis", "Condromalacia patelar", "Insuficiencia respiratoria", "Polidactilia", "Acromegalia",
  "Adherencia intrauterina", "Anemia ferropénica", "Posmenopausia", "Sinusitis aguda", "Enfermedad glomerular lúpica", "Osteosarcoma",
  "Glioma en adultos", "Aneurisma de la aorta torácica", "Infecciones de vías respiratorias de repetición (o recurrentes)", "Quiste pilonidal", "Fractura de mano", "Hepatitis autoinmunitaria",
  "Gonartrosis", "Radiculopatía cervical", "Enfisema pulmonar", "Rítides facial", "Osteomielitis", "Retinopatía hipertensiva",
  "Trastorno de personalidad histriónica", "Infecciones de vías urinarias", "Aneurisma aórtico abdominal", "Dolor crónico", "Tumor tiroideo", "GERD",
  "Sindactilia", "Hipertensión renal", "Prolactinoma", "Evento vascular cerebral", "Enfermedad de Cushing", "Corea de Huntington",
  "Anemia aplásica adquirida", "Desnutrición infantil", "Defectos de refracción", "Cáncer tiroideo (carcinoma medular)", "Accidente cerebrovascular cardioembólico", "Alergias en ambientes interiores",
  "Prediabetes", "Hemangioma", "Neuropatias Compresivas", "Adenocarcinoma del útero", "Bebé de madre diabética", "Anemia hemolítica",
  "Cistitis en niños", "Eyaculación retrasada", "Exotropía", "Membrana epirretiniana macular", "Boca de trinchera", "Tinnitus",
  "Glaucoma de ángulo abierto", "Cifosis postural", "Manos entumidas", "Arterioesclerosis de las extremidades", "Soplo cardíaco", "Embolia arterial",
  "Hipertensión renovascular", "Tumor pituitario (tumor de la hipófisis)", "Dolor lumbar inespecífico", "Cáncer de la vulva", "Embarazo múltiple", "Síndrome de sueño y vigilia irregulares",
  "Alcohol en el embarazo", "Conducto nasolagrimal obstruido", "Pigmentación severa dental", "Deslizamiento de la epífisis capital femoral", "Cálculos vesicales", "Acné quístico",
  "Esguince cervical", "Infección de la piel por bacterias", "Hipertensión arterial sistémica", "Embarazo molar", "Arco alto", "Pérdida gestacional recurrente",
  "Síndrome de dolor pélvico crónico", "Enfermedad del sueño", "Terror nocturno", "Trastornos neurocognitivos", "Tetralogía de Fallot", "Infecciones de la glándula salival",
  "Gangrena", "Gangrena de tejidos blandos", "Adenocarcinoma del estómago", "Cirrosis biliar primaria", "Uña del pie encarnada", "Pólipos cervicales",
  "Demencia senil", "Cáncer de vagina", "Acidosis metabólica", "Apnea en recién nacidos", "Vaginitis", "Tuberculosis",
  "Herpes genital", "Hipertensión arterial pulmonar", "Endotropía", "Gota crónica", "Prolapso de disco intervertebral", "Acidosis tubular distal renal",
  "Hemorragia subaracnoidea", "Eritema tóxico del neonato", "Submordida", "Tendinitis bicipital", "Glaucoma de ángulo cerrado", "Reacción anafiláctica",
  "Amebiasis hepática", "Hipotensión", "Cardiomiopatía hipertrófica (CMH)", "Pseudoartrosis", "Espolón calcáneo y fascitis plantar", "Síndrome de Edwards",
  "Hiperplasia endometrial benigna", "Trastorno de la personalidad evasiva", "Entropión", "Visión corta", "Trastorno de la personalidad pasivo-agresiva", "Enterocolitis necrosante",
  "Angiodisplasia del colon", "Carcinoma hepatocelular", "Fractura de la base del metatarso", "Vértigo Central", "Absceso hepático bacteriano", "Agua en el pulmón",
  "Shock séptico", "Colestasis", "Andropausia", "Artritis reactiva", "Infección sinusal", "Conjuntivitis aguda",
  "Pinguécula", "Angina de Ludwig", "Hiperacusia", "Síndrome de bradicardia-taquicardia", "Hernia discales", "Síndrome de Ehlers-Danlos",
  "Codependencia emocional y heridas de infancia", "HIV/SIDA", "Enfermedad pulmonar intersticial difusa", "Vacío", "Diarrea aguda con deshidratación", "Bronquiectasia",
  "Lesiones del tendón rotuliano", "Estomatitis ulcerativa", "Glomeruloesclerosis diabética", "Síndrome de Guillain-Barré", "Autolesiones", "Úlceras por presión",
  "Diástasis de rectos", "Tromboembolia venosa", "Neuropatía del nervio radial", "Trastornos del climaterio y menopausia", "Colitits ulcerativa", "Cáncer de las vías biliares",
  "Onicocriptosis", "Tiña", "Alopecia universal", "Espolón calcáneo", "Síndrome de Asperger", "Epicondilitis lateral",
  "Intersexualidad", "Bronquitis", "Irratibilidad", "Uremia", "Neuritis óptica", "Trastorno convulsivo",
  "Retinopatía de la prematuridad", "Reacción alérgica a una droga (medicamento)", "Shock anafiláctico", "Carcinoma papilar de la tiroides", "Malformaciones congénitas", "Tumor de Wilms",
  "Cáncer de paratiroides", "Gastritis por Helicobacter pylori", "Cor pulmonale", "Tumor hipofisario", "Síndrome de Cushing", "Meningitis",
  "Conjuntivitis del neonato", "Trastornos del sueño (insomnio)", "Hombro de lanzador", "Cicatrices", "Insuficiencia renal terminal", "Apnea de la prematuridad",
  "Cáncer de células transicionales de la pelvis renal o del uréter", "Perforación de la membrana timpánica", "Estrabismo divergente", "Arteriopatía periférica", "Adenoma hepático", "Enfermedad de las arterias coronarias o coronariopatía",
  "Tumor del hígado", "Telangiectasia", "Síndrome de Barrett", "Enfermedad mano-pie-boca", "Absceso subcutáneo", "Infecciones Recurrentes de vías respiratorias",
  "Leucemia aguda de la infancia", "Infección viral de las vías respiratorias altas", "Clamidia", "Sífilis", "Neutropenia", "Cistitis recurrente",
  "Ataxia cerebelosa", "Otosclerosis", "DDC", "Depresión unipolar", "Quiste de retención mucosa", "Miocardiopatía dilatada",
  "Taquicardia supraventricular paroxística (TSVP)", "Hipertensión arterial en bebés", "Ronchas", "Síndrome de oclusión de la arteria carótida", "Enfisema", "Presbiacusia",
  "Enfermedad de Addison", "Transexualismo", "Parasitosis", "Cáncer: leucemia infantil aguda (LLA)", "Embarazo anembrionario (Huevo huero)", "Dolor asociado con la ovulación",
  "Desprendimiento prematuro de placenta", "Brucelosis", "Celulitis orbitaria", "Síndrome psiquiátrico de causa orgánica", "Espina bífida", "Convulsión generalizada",
  "Depresión psicótica", "Malformaciones craneofaciales", "Parálisis de las cuerdas vocales", "Degeneración marginal pelúcida", "Infección de los senos paranasales", "Onfalocele",
  "Rinitis no alérgica", "Malformaciones arteriovenosas", "Mediastinitis", "Neuralgia", "HPB", "Demencia con los cuerpos de Lewy",
  "Cirrosis o hepatitis alcohólica", "Acrocordones", "Coma diabético hiperosmolar hiperglucémico", "Pérdida del cabello en mujeres", "Leucemia aguda mieloide", "Celulitis preseptal",
  "Faringitis estreptocócica", "Manchas en la piel", "Diabetes mellitus tipo 1 y tipo 2 en niños, adolescentes y adultos", "Nódulo pulmonar solitario", "Astrocitoma en niños", "Fracturas de la órbita",
  "Falla crónica de los riñones", "Problemas de memoria en adultos mayores", "Prostatitis aguda", "Anillo de Schatzki", "Fistula anal", "Absceso rectal",
  "Pólipos intestinales", "Embolia cerebral", "Disfagia", "Diabetes insípida central", "Hepatitis B", "Fibrosis pulmonar idiopática",
  "Fibromioma", "Dolor en mitad del ciclo menstrual", "Celulitis periorbitaria", "Esclerosis lateral amiotrófica", "Trastornos renales y urológicos", "Estomatitis candidósica",
  "Inflamación de las articulaciones", "Dacriostenosis", "Granulomatosis de Wegener", "Miositis", "Criptodoncia", "Coroidopatía serosa central",
  "Queratitis por herpes simple", "Otitis media crónica", "Síndrome del periforme", "Insuficiencia cardíaca congestiva", "Hemorroides trombosadas", "Hiperparatiroidismo primario",
  "Cáncer oral", "Cefalea en brotes", "Mano Reumática", "Hemotórax", "Familia de tumores de Ewing", "Infecciones",
  "Insuficiencia Adrenal", "Síndrome de Morquio", "Síndrome de carencia materna", "ELA", "Vejiga irritable", "Polineuropatía sensitivomotora",
  "Luxación parcial del codo", "Candidiasis oral (Algodoncillo)", "Hemorragia subconjuntival", "Antepié varo", "Poliquistosis renal", "Derrame subdural",
  "Apoplejía hipofisaria", "Acidosis tubular renal proximal", "Enfermedad renal poliquística autosómica dominante", "Convulsión inducida por fiebre", "Queratitis bacteriana"
];
